# -*- coding: utf-8 -*-
"""Liens externes vers les paroles de chaque morceau. Clé : identifiant Spotify.

Relevés lors du chantier de sourcing des paroles (Genius en priorité, puis
lyrics.com / songlyrics.com / letras.com selon disponibilité) : voir
genius-releve.html, musixmatch-releve.html et paroles-44(-v2).html dans
l'historique du projet Claude pour la méthode.

`SEARCH` marque les morceaux pour lesquels aucune page de paroles précise n'a
été confirmée : l'URL stockée ici sert seulement à la vérification de
complétude du build (chaque morceau doit avoir une entrée) ; à l'affichage,
build.py remplace ce lien par une recherche DuckDuckGo (nom de l'artiste +
titre + « lyrics ») générée à la volée, et le lien public le dit plutôt que
de laisser croire à une fiche trouvée.
"""

LYRICS = {
    '0QA1xpUuqHDHWZhi0eAbH7': 'https://genius.com/Sophie-its-okay-to-cry-lyrics',
    '1huN927tTdSiwF90FBHXkT': 'https://genius.com/Sophie-immaterial-lyrics',
    '2rN1ODOsaNfYu782rw36jR': 'https://genius.com/Sophie-faceshopping-lyrics',
    '7tktCNlB0877dhdPZSRb7T': 'https://genius.com/Sophie-is-it-cold-in-the-water-lyrics',
    '48XnOS1vTyzqaPps0Dalzp': 'https://genius.com/Sophie-ponyboy-lyrics',
    '4lUlYGT5VvZWN3GBDIc9KT': 'https://genius.com/Arca-nonbinary-lyrics',
    '3XdXixlx3MoVzfL7pu9hx6': 'https://genius.com/Arca-time-lyrics',
    '5rOzcHIZaF038jMeHkUZR0': 'https://genius.com/Arca-reverie-lyrics',
    '3r0gvoaAkWmLdJO4UUv94v': 'https://genius.com/Arca-desafio-lyrics',
    '6RJiY28t9jWpdy1JkUhNgK': 'https://genius.com/Arca-mequetrefe-lyrics',
    '4OI2gBlHqyNks8cbIBIKYw': 'https://genius.com/search?q=Angel-Ho+Like+A+Girl',
    '6JZfK4Z75nZm3VcZOVrpy0': 'https://genius.com/Anohni-drone-bomb-me-lyrics',
    '3IDQXyHYuX2rdLnNfVzT3g': 'https://genius.com/Anohni-4-degrees-lyrics',
    '6jiumfqTwOpXW6PDzsIBKl': 'https://genius.com/search?q=Sonja+Sajzor+I+Keep+Doing+This+to+Myself',
    '2BQZhUPXdP9Nk1X84c7PtP': 'https://genius.com/Lauren-auder-unseen-lyrics',
    '5e0ZXu358l51ckAZvai2Ef': 'https://genius.com/Bulent-ersoy-geceler-lyrics',
    '0XIutL5epZuYV91bhCfFsR': 'https://genius.com/Bulent-ersoy-umit-hrsz-lyrics',
    '1AHPsqF3EtHeWpOM06Y3Y4': 'https://genius.com/Antony-and-the-johnsons-hope-theres-someone-lyrics',
    '1jFN0stMzLepoPxvPywGZj': 'https://genius.com/Kim-petras-heart-to-break-lyrics',
    '5pkemVhnBiIzMs2NLsXomQ': 'https://genius.com/Kim-petras-clarity-lyrics',
    '4xhYxKvAxtrRd83MiqOy29': 'https://genius.com/Kim-petras-i-dont-want-it-at-all-lyrics',
    '75HFFq9W7Em0dTBG8QeGcT': 'https://genius.com/Kim-petras-there-will-be-blood-lyrics',
    '71yN0yrHej3jhKXewbmtEh': 'https://genius.com/Kim-petras-coconuts-lyrics',
    '6yAc1rz1RXRlYJac99xusK': 'https://genius.com/search?q=Tone+Sekelius+Girls+%26+Dolls',
    '1toNKayLMeCcVlsLGXJl7n': 'https://genius.com/Laura-les-haunted-lyrics',
    '1w0AFg23E67l57A3RMiXjC': 'https://genius.com/Femtanyl-p3t-lyrics',
    '2sVjF25Z4JTJxi9BXm5GtJ': 'https://genius.com/Femtanyl-act-right-lyrics',
    '6XeW8fjwoAFQeQpYojPtVI': 'https://genius.com/Femtanyl-girl-hell-1999-lyrics',
    '5iAE3uBqaZm9aHUx9yy6a0': 'https://genius.com/Femtanyl-katamari-lyrics',
    '7kvQptbfqq5b4MWRQOMrZC': 'https://genius.com/Femtanyl-and-issbrokie-nastywerkkkk-lyrics',
    '724utiMbqUfT1g3tqbfQYu': 'https://genius.com/Underscores-spoiled-little-brat-lyrics',
    '1PEPcLm2QEo0HCRIhQjPq1': 'https://genius.com/Underscores-second-hand-embarrassment-lyrics',
    '0ZeVhHgvMsF6dqo2AFSfut': 'https://genius.com/Tamagotchi-massacre-im-two-years-on-hormones-and-im-still-sad-i-want-a-refund-lyrics',
    '0VNjaRcmIowjLbPtYDhLuh': 'https://genius.com/Underscores-your-favorite-sidekick-lyrics',
    '54n3iwz9mr7yxZi1EOX1Mz': 'https://genius.com/Underscores-and-gabby-start-locals-girls-like-us-lyrics',
    '5dIPCgTEDagbcs5QGmni8V': 'https://genius.com/search?q=MON%C4%80E+CISPHOBIC',
    '5iTzaatezJzsUhX1QjT0Kp': 'https://genius.com/Petal-supply-person-lyrics',
    '51NYFGDXYKS4FkRqkw98hx': 'https://genius.com/Chase-icon-like-me-lyrics',
    '1d3hBkCcMvVzsZjaMiVvNs': 'https://genius.com/Chase-icon-srs-lyrics',
    '0Irj6PuEEGzi7JGJvAhdZ8': 'https://genius.com/Mel-4ever-i-cant-quit-lyrics',
    '18QS9wnUr7DOhMb73monpK': 'https://genius.com/Mel-4ever-and-ayesha-erotica-tongues-lyrics',
    '7EPHu29KqhsGk4dZAjM0o4': 'https://genius.com/Stef-aranas-and-m1ss-jade-so-cvnty-20-lyrics',
    '1RXkdiCc4TtwPacmIKyUnX': 'https://genius.com/Ayesha-erotica-vacation-bible-school-lyrics',
    '2gmwvGC1yOw8NdMcZE8nfo': 'https://genius.com/Ayesha-erotica-literal-legend-lyrics',
    '1XD4K4CGAKTIBmFpvuaFru': 'https://genius.com/Jane-remover-dancing-with-your-eyes-closed-lyrics',
    '3RLI8S7KpEZs4SqePGjM2R': 'https://genius.com/Estelle-allen-dui-lyrics',
    '7n7GrVTBmZMG4EULD5g0i3': 'https://genius.com/Quinn-warm-and-fuzzy-lyrics',
    '6WkiWn8bf8S29wSk0VwK7h': 'https://genius.com/Frost-children-falling-lyrics',
    '06kFuqzhMk4E6IYeO0sTfx': 'https://genius.com/Frost-children-and-kim-petras-radio-lyrics',
    '2Of9piZALXa4CC7Unxoeeg': 'https://genius.com/Villano-antillano-klk-lyrics',
    '4hceSKjrkDTO0nMKFcb3sj': 'https://genius.com/Bizarrap-and-villano-antillano-villano-antillano-bzrp-music-sessions-vol-51-66-lyrics',
    '29Ga6IgetN8Xah85ZHZ8AC': 'https://genius.com/Samantha-hudson-and-villano-antillano-full-lace-y-el-tuck-lyrics',
    '376mhFeloWqzQJQsqZpm9A': 'https://genius.com/search?q=Pupi+Poisson+Las+Defectos',
    '78iHtTxYIK2mD6oL6lXqFF': 'https://genius.com/Gad-yola-travesti-del-peru-lyrics',
    '5PMtJGEDIO0eIToF0YRUQ5': 'https://genius.com/Jedet-and-mygal-veneno-pa-tu-piel-lyrics',
    '2KryklrVDGmWL8IvoGNbb5': 'https://genius.com/search?q=Umlilo+Zulu+Lami',
    '1YsFdaP9QG9NhjYS3o0g5P': 'https://genius.com/Titica-olha-o-boneco-lyrics',
    '5lz6U9dCYBmEY6oLrW22VE': 'https://www.letras.com/titica/olha-a-banana-part-kelmer-pastilha-e-mauro-xtraga/',
    '0a0CwJBn8lmT5ifk63EUbP': 'https://genius.com/Against-me-true-trans-soul-rebel-lyrics',
    '4b1Y41U44kP7gzO7MUNGbe': 'https://genius.com/Against-me-transgender-dysphoria-blues-lyrics',
    '14uL43Gg4ujizaATehrryk': 'https://genius.com/Against-me-the-ocean-lyrics',
    '0wIpjjcXFgGtJUmBIRAAju': 'https://genius.com/Against-me-black-me-out-lyrics',
    '2DUAIlPmzV2is5OQIZASUA': 'https://genius.com/Anita-velveeta-t4t-lyrics',
    '7yeRNInEt2DOFYW0BkETEe': 'https://genius.com/Ezra-furman-restless-year-lyrics',
    '4NYRtDYROQW2D2ctcylcri': 'https://genius.com/Gloss-targets-of-men-lyrics',
    '3bnvoYUrPkgh0E3ZeYZ3me': 'https://genius.com/Changeline-octopuslady-lyrics',
    '20JYh6XUjLjiN1CyJ32ZiY': 'https://genius.com/Changeline-anarconnasse-lyrics',
    '7lc4ue2LiSfYRaABxq4YkT': 'https://genius.com/Changeline-jedetestelafrancept1-il-y-aura-pas-de-pt2-english-translation-lyrics',
    '0ZQLRkRyn3300WyapdPoWT': 'https://genius.com/Thea-fra-cavale-cavale-lyrics',
    '3RXajeZOzqXWrQwLDfTzKK': 'https://genius.com/Thea-fra-juste-amis-lyrics',
    '0bWpWsvZeTTNLQ9nuXqKIN': 'https://genius.com/Thea-fra-guillotine-lyrics',
    '7zBUh6s2Ca8eAURfnVHCTS': 'https://genius.com/Thea-fra-anxiolytiques-lyrics',
    '3ShIGvHRm0q9iIDowUMjls': 'https://genius.com/Laura-jane-grace-the-best-ever-death-metal-band-in-denton-lyrics',
    '1IF61ped0XehHvw2CFXP3B': 'https://genius.com/Jayne-county-man-enough-to-be-a-woman-lyrics',
    '0VhGzYfT2ZOFz31b5IH7yJ': 'https://genius.com/search?q=Marie+France+Un+gar%C3%A7on+qui+pleure',
    '3zGmkzXqXsXYVlGzJFpgCW': 'https://genius.com/search?q=Venus+de+Mars+and+All+the+Pretty+Horses+Boys',
    '7GAI6zWpmst6dSfu1wIA1O': 'https://genius.com/search?q=Venus+de+Mars+and+All+the+Pretty+Horses+White+Horses',
    '3Vk1AHIh1CoiQzFroldMhO': 'https://genius.com/search?q=Venus+De+Mars+Take+My+Shoulder+%28feat.+Laura+Jane+Grace%29',
    '2inX5xyazBvcZYLx3wRBwh': 'https://genius.com/search?q=Tingtongketz+Berubah',
    '73xUwV4DkcelY7seMyY0PY': 'https://genius.com/Beth-elliott-lady-on-the-subway-lyrics',
    '4dtyeDMnVKKo89QbbDtD5M': 'https://genius.com/search?q=Beth+Elliott+Ballad+of+the+Oklahoma+Women%27s+Liberation+Front',
    '02L1ngagXNRt8W3Flbe9Sw': 'https://genius.com/Namoli-brennet-boy-in-a-dress-lyrics',
    '7KtbrK74NNA4ySRZ49DC7R': 'https://genius.com/Mya-byrne-where-the-lavender-grows-lyrics',
    '3qBg6BeHJlGgwl5aCa09EC': 'https://genius.com/Left-at-london-revolution-lover-lyrics',
    '3z4KIXgkhLauhNP3ubB8cF': 'https://genius.com/Left-at-london-6-feet-lyrics',
    '2CznvTOsuLh0USpHJqEc6V': 'https://genius.com/June-jones-motorcycle-lyrics',
    '2jFP4mAHcDmGe7DEKKLyJa': 'https://genius.com/Jasmine4t-skin-on-skin-lyrics',
    '0kNjtDBxrpjJTZn9w5Eq3C': 'https://genius.com/Vivek-shraya-i-take-all-the-blame-lyrics',
    '2fB0l9upVjg0QTeMyrIVtc': 'https://genius.com/Vivek-shraya-part-time-woman-lyrics',
    '5nnBHHzUDOGvdMBiXofB00': 'https://www.songlyrics.com/luisa-almaguer/exiliades-lyrics/',
    '6JGJdnIbq4UqKgzFaOIXwE': 'https://genius.com/Luisa-almaguer-mataronomatar-lyrics',
    '3nxFYWNFG2qGYEuhEzomtO': 'https://genius.com/search?q=Susy+Shock+Vidalita%2C+Vidalita',
    '3BYSoeWlqUgIwfY77C8VgE': 'https://www.letras.com/la-bruja-de-texcoco/te-de-malvon/',
    '1QrL7ucS71Ih4HXBOsuajv': 'https://www.letras.com/la-bruja-de-texcoco/laabe-muxhe/',
    '4ltqfN12ohaVZdM6C45gMg': 'https://genius.com/Ethel-cain-american-teenager-lyrics',
    '3MZjOGeXhpHbQ9ESMNFFnH': 'https://genius.com/Steam-powered-giraffe-honeybee-lyrics',
    '2Ff6Ghw8TRJGuAbJamtt4X': 'https://genius.com/Superknova-serotonin-serenade-lyrics',
    '1ovz0bZeO5YTBQTXIFf5Am': 'https://genius.com/Daniela-vega-ombra-mai-fu-lyrics',
    '5P9EKJfOZtuwtTR5C5362i': 'https://genius.com/Daniela-vega-sposa-son-disprezzata-lyrics',
    '1OpCGPKSq4IfpvLptsSMR9': 'https://genius.com/search?q=Tona+Brown+I%2C+Too',
    '5l2zYkyTXtYa8xk965ofqD': 'https://genius.com/search?q=Tona+Brown+Dream+Variations',
    '5dtUOwEmnDAzsdodWJk4DA': 'https://genius.com/Jackie-shane-any-other-way-lyrics',
    '5NnQ2xIeHDKc1B19rxfcV3': 'https://genius.com/search?q=Veronica+Klaus+I+Will+Survive',
    '56xBg5e9rfrFqcqa4llUw7': 'https://genius.com/Jinkx-monsoon-just-me-the-gender-binary-blues-lyrics',
    '5WttRLHcZHhaIii5KwKh3Y': 'https://genius.com/Shea-diamond-i-am-her-lyrics',
    '0gm0OruZdJlu8jamJe5OCh': 'https://genius.com/Shea-diamond-keisha-complexion-lyrics',
    '3BqWvhPear6eKPwhwJRFpO': 'https://genius.com/Mila-jam-bruised-lyrics',
    '7luHAaHXty1Nl3AcscZIDT': 'https://genius.com/Mila-jam-faces-lyrics',
    '2qpx5shtNEO1DuK8iEoJoB': 'https://genius.com/Peppermint-best-sex-lyrics',
    '3ApVA7ID6PkS0fGzNF4mFw': 'https://genius.com/search?q=Peppermint+A+Girl+Like+Me',
    '4ED8r6i90zmUG4kfbiVoou': 'https://genius.com/Ah-mer-ah-su-heartbreaker-lyrics',
    '0rK7QTyYjhPFadLH2YDl84': 'https://genius.com/search?q=Our+Lady+J+Picture+of+a+Man',
    '4QnHaiWq1oJiTgMnRFE0q8': 'https://www.letras.com/zemmoa/mi-amor-soy-yo-part-tessa-ia-y-trans-x/',
    '0DZapO0gUF8XZpk2bu8AeL': 'https://genius.com/search?q=Aderet+%D7%94%D7%99%D7%95+%D7%9C%D7%99%D7%9C%D7%95%D7%AA',
    '07m5UbUHOQCofRK16k83Eg': 'https://genius.com/search?q=Shyraa+Roy+Duniya',
    '5srzGYocC4qYFvckQm5AfC': 'https://genius.com/search?q=Haiifa+Magic+To2i+W+Far2a3i',
    '4X6PkqzKUvWWKoq4YiiM1V': 'https://genius.com/Harisu-snow-white-lyrics',
    '7l8D5tXUVsdq95VQWn034C': 'https://genius.com/Harisu-a-dream-of-knowing-love-lyrics',
    '1EPYnBjYhYHcNthEnVWk18': 'https://genius.com/Harisu-never-mind-lyrics',
    '4Ykmj47fulJ1FTeCXctW91': 'https://genius.com/Huong-giang-idol-anh-ta-bo-em-roi-lyrics',
    '1N1F6UsRGILux57U0YbxJQ': 'https://genius.com/search?q=Cindy+Th%C3%A1i+T%C3%A0i+Gi%E1%BB%8Dt+T%C3%ACnh',
    '0NOume8OgBz4FCnP1QVr9A': 'https://genius.com/search?q=Bell+Nuntita+Paradise',
    '46uGvJVhYHOVRRNnRPbkYm': 'https://www.shazam.com/song/1462900844/mantan-tanpa-status-feat-dede-satria',
    '0GSW6V6GJc4xYi8c5jOu60': 'https://genius.com/search?q=Ai+Haruna+%E3%81%95%E3%81%9D%E3%82%8A%E5%BA%A7%E3%81%AE%E5%A5%B3',
    '6EjxYTyXiBzJz6PeOvPiou': 'https://genius.com/search?q=Ataru+Nakamura+%E3%81%8D%E3%81%BF%E3%81%8C%E3%81%99%E3%81%8D%E3%81%A0%E3%82%88',
    '4yBfzgV6YA9dTKP8KUD35j': 'https://www.songlyrics.com/lia-larsson/vi-ar-sverige-vm-lat-2023-lyrics/',
    '0pe5NUU9uGwFpj637ot84D': 'https://genius.com/search?q=Patricia+Ribeiro+Conquistador',
    '4Zhxtm6x56wEiRtSMAl28n': 'https://genius.com/Urias-diaba-lyrics',
    '1RmXibCbfLIVrN8ZRdoYbW': 'https://genius.com/Urias-foi-mal-lyrics',
    '4P9LdSPrnQl7KQwml4DUtq': 'https://genius.com/Liniker-baby-95-lyrics',
    '1AFPmwB6mGMCcMI2hFh7c8': 'https://genius.com/Linn-da-quebrada-enviadescer-lyrics',
    '6D7zTed8zrkuKBPca2AqSI': 'https://genius.com/Irmas-de-pau-medley-do-submundo-lyrics',
    '7bNgXJ9MgGG7xOkyz9SLOY': 'https://genius.com/Pedro-sampaio-irmas-de-pau-mc-gw-and-tasha-kaiala-sequencia-cunt-lyrics',
    '4WhyfhjZaX6AVjAZslQAFs': 'https://genius.com/Pepita-parceira-lyrics',
    '3FysLYckiMCMzjYLIgo45U': 'https://genius.com/Backxwash-black-sailor-moon-lyrics',
    '37OSQm8Gy5strUT24vn6ef': 'https://genius.com/Backxwash-i-lie-here-buried-with-my-rings-and-my-dresses-lyrics',
    '3QF7smzmw2WWm7M1jt2Rac': 'https://genius.com/Angel-maxine-wo-fie-lyrics',
    '6JrmHzxhaaavRtlXTOhm63': 'https://genius.com/Quay-dash-queen-of-this-shit-lyrics',
    '2iqTYCPRTqojxM7QJvBtk2': 'https://genius.com/Ms-boogie-breakdown-lyrics',
    '3eBY8aZZdWNnNhNbc8B0yp': 'https://genius.com/search?q=Andra+Venus+Power',
    '1RkB4Dk0CDzpaSySq91JEA': 'https://www.musixmatch.com/lyrics/SASHA-SATHYA-4/AKA-LESBIANA-SERPIENTA',
    '4UfEEnq70NgLeq7NRfXPiD': 'https://genius.com/Lalla-rami-inchallah-lyrics',
    '5nWecUJF2pytSxsSpylzZw': 'https://genius.com/Lalla-rami-9a7ba-lyrics',
    '5Gp1fkuPV7CPtzKHfMH0kd': 'https://genius.com/Ptite-soeur-and-neophron-anfo-lyrics',
    '0A2tFUYLertZLltvvY5uyr': 'https://genius.com/Ptite-soeur-and-gemroz-kayfabe-lyrics',
    '2lgwylOpGMtkvhwdnUOArt': 'https://genius.com/search?q=Romy+Haag+Memories+Are+Made+Of+This+-+Radio',
    '4CuivW1JgPauXPA4wYsf5K': 'https://genius.com/search?q=Coccinelle+Chercher+la+femme',
    '3qDqg53YIe9mM5Ehx9v9FZ': 'https://genius.com/Cristina-la-veneno-el-rap-de-la-veneno-lyrics',
    '6fd79PtewFZgLXYiIYhhLJ': 'https://genius.com/Ella-bra-la-dracula-lyrics',
    '2PaTBoG5uDz6H3xPhnnDLz': 'https://genius.com/Trevi-moran-digital-empathy-lyrics',
    '4OF1mdSkA2z05DSwHNKVnz': 'https://genius.com/Wendy-guevara-hasta-que-salga-el-sol-lyrics',
    '4DfHQvIAZmSmqcZbuO80sZ': 'https://genius.com/Dylan-mulvaney-days-of-girlhood-lyrics',
}

# Morceaux sans fiche de paroles confirmée : le lien public (généré par
# build.py) pointe vers une recherche DuckDuckGo, pas vers l'URL ci-dessus.
SEARCH = {
    '4OI2gBlHqyNks8cbIBIKYw',
    '6jiumfqTwOpXW6PDzsIBKl',
    '6yAc1rz1RXRlYJac99xusK',
    '5dIPCgTEDagbcs5QGmni8V',
    '376mhFeloWqzQJQsqZpm9A',
    '2KryklrVDGmWL8IvoGNbb5',
    '0VhGzYfT2ZOFz31b5IH7yJ',
    '3zGmkzXqXsXYVlGzJFpgCW',
    '7GAI6zWpmst6dSfu1wIA1O',
    '3Vk1AHIh1CoiQzFroldMhO',
    '2inX5xyazBvcZYLx3wRBwh',
    '4dtyeDMnVKKo89QbbDtD5M',
    '3nxFYWNFG2qGYEuhEzomtO',
    '1OpCGPKSq4IfpvLptsSMR9',
    '5l2zYkyTXtYa8xk965ofqD',
    '5NnQ2xIeHDKc1B19rxfcV3',
    '3ApVA7ID6PkS0fGzNF4mFw',
    '0rK7QTyYjhPFadLH2YDl84',
    '0DZapO0gUF8XZpk2bu8AeL',
    '07m5UbUHOQCofRK16k83Eg',
    '5srzGYocC4qYFvckQm5AfC',
    '1N1F6UsRGILux57U0YbxJQ',
    '0NOume8OgBz4FCnP1QVr9A',
    '0GSW6V6GJc4xYi8c5jOu60',
    '6EjxYTyXiBzJz6PeOvPiou',
    '0pe5NUU9uGwFpj637ot84D',
    '3eBY8aZZdWNnNhNbc8B0yp',
    '2lgwylOpGMtkvhwdnUOArt',
    '4CuivW1JgPauXPA4wYsf5K',
}
