# -*- coding: utf-8 -*-
"""Dates de première publication des morceaux de la playlist.

Clé : identifiant Spotify, la même que dans tracks.py.

first_public : première existence publique du morceau, tous supports confondus,
               live non enregistré compris. C'est la clé de tri.
first_record : année d'enregistrement, quand elle est connue ET distincte de la
               parution. L'écart entre les deux mesure une publication empêchée.
kind         : first | earliest_known | approx
status       : verified | partial | unresolved | absent
precision    : day | month | year | decade

Une date MusicBrainz non recoupée reste partial et earliest_known : la base donne
la plus ancienne parution qu'elle connaît, pas la première qui ait existé.
"""

YEARS = {
    # SOPHIE — It's Okay To Cry  [pilote]
    "0QA1xpUuqHDHWZhi0eAbH7": {
        "first_public": "2017-10-19",
        "first_record": None,
        "precision": "day",
        "kind": "first",
        "spotify": "2018-06-15",
        "status": "verified",
        "source": "The FADER, article of 19 October 2017 premiering the video",
        "url": "https://www.thefader.com/2017/10/19/sophie-its-okay-to-cry",
        "checked": "2026-09-04",
        "note": "The article premieres the video on 19 October and announces the streaming release for the 23rd. The song is public on the 19th.",
    },
    # SOPHIE — Immaterial
    "1huN927tTdSiwF90FBHXkT": {
        "first_public": "2017-10-30",
        "first_record": None,
        "precision": "day",
        "kind": "first",
        "spotify": "2018-06-15",
        "status": "verified",
        "source": "MusicBrainz, release SOPHIE: LIVE AT TERAGRAM BALLROOM, 30 October 2017, tracklist read",
        "url": "https://musicbrainz.org/search?query=SOPHIE+LIVE+AT+TERAGRAM+BALLROOM&type=release",
        "checked": "2026-09-04",
        "note": "The song appears in this concert, eight months before the album. Confirmed on the tracklist.",
    },
    # SOPHIE — Faceshopping
    "2rN1ODOsaNfYu782rw36jR": {
        "first_public": "2017-10-30",
        "first_record": None,
        "precision": "day",
        "kind": "first",
        "spotify": "2018-06-15",
        "status": "verified",
        "source": "MusicBrainz, release SOPHIE: LIVE AT TERAGRAM BALLROOM, 30 October 2017, tracklist read",
        "url": "https://musicbrainz.org/search?query=SOPHIE+LIVE+AT+TERAGRAM+BALLROOM&type=release",
        "checked": "2026-09-04",
        "note": "The song appears in this concert, four months before the single. Confirmed on the tracklist.",
    },
    # SOPHIE — Is It Cold In The Water?
    "7tktCNlB0877dhdPZSRb7T": {
        "first_public": "2017-10-30",
        "first_record": None,
        "precision": "day",
        "kind": "first",
        "spotify": "2018-06-15",
        "status": "verified",
        "source": "MusicBrainz, release SOPHIE: LIVE AT TERAGRAM BALLROOM, 30 October 2017, tracklist read",
        "url": "https://musicbrainz.org/search?query=SOPHIE+LIVE+AT+TERAGRAM+BALLROOM&type=release",
        "checked": "2026-09-04",
        "note": "Date already held, confirmed by the concert tracklist.",
    },
    # SOPHIE — Ponyboy
    "48XnOS1vTyzqaPps0Dalzp": {
        "first_public": "2017-06-14",
        "first_record": None,
        "precision": "day",
        "kind": "earliest_known",
        "spotify": "2018-06-15",
        "status": "partial",
        "source": "MusicBrainz, first-release-date of the recording, title and artist match checked",
        "url": "https://musicbrainz.org/search?query=SOPHIE%20Ponyboy&type=recording",
        "checked": "2026-09-04",
        "note": "A compilation sits among the known releases.",
    },
    # Arca — Nonbinary
    "4lUlYGT5VvZWN3GBDIc9KT": {
        "first_public": "2020-04-30",
        "first_record": None,
        "precision": "day",
        "kind": "earliest_known",
        "spotify": "2020-06-26",
        "status": "partial",
        "source": "MusicBrainz, first-release-date of the recording, title and artist match checked",
        "url": "https://musicbrainz.org/search?query=Arca%20Nonbinary&type=recording",
        "checked": "2026-09-04",
        "note": "A compilation sits among the known releases.",
    },
    # Arca — Time
    "3XdXixlx3MoVzfL7pu9hx6": {
        "first_public": "2020-05-20",
        "first_record": None,
        "precision": "day",
        "kind": "earliest_known",
        "spotify": "2020-06-26",
        "status": "partial",
        "source": "MusicBrainz, first-release-date of the recording, title and artist match checked",
        "url": "https://musicbrainz.org/search?query=Arca%20Time&type=recording",
        "checked": "2026-09-04",
        "note": "A compilation sits among the known releases.",
    },
    # Arca — Reverie
    "5rOzcHIZaF038jMeHkUZR0": {
        "first_public": "2017-03-17",
        "first_record": None,
        "precision": "day",
        "kind": "earliest_known",
        "spotify": "2017-04-07",
        "status": "partial",
        "source": "MusicBrainz, first-release-date of the recording, title and artist match checked",
        "url": "https://musicbrainz.org/search?query=Arca%20Reverie&type=recording",
        "checked": "2026-09-04",
        "note": "",
    },
    # Arca — Desafío
    "3r0gvoaAkWmLdJO4UUv94v": {
        "first_public": "2017-04-07",
        "first_record": None,
        "precision": "day",
        "kind": "earliest_known",
        "spotify": "2017-04-07",
        "status": "partial",
        "source": "MusicBrainz, first-release-date of the recording, title and artist match checked",
        "url": "https://musicbrainz.org/search?query=Arca%20Desaf%C3%ADo&type=recording",
        "checked": "2026-09-04",
        "note": "A compilation sits among the known releases.",
    },
    # Arca — Mequetrefe
    "6RJiY28t9jWpdy1JkUhNgK": {
        "first_public": "2020-06-17",
        "first_record": None,
        "precision": "day",
        "kind": "earliest_known",
        "spotify": "2020-06-26",
        "status": "partial",
        "source": "MusicBrainz, first-release-date of the recording, title and artist match checked",
        "url": "https://musicbrainz.org/search?query=Arca%20Mequetrefe&type=recording",
        "checked": "2026-09-04",
        "note": "A compilation sits among the known releases.",
    },
    # Angel-Ho, K Rizz — Like A Girl
    "4OI2gBlHqyNks8cbIBIKYw": {
        "first_public": "2019-03-01",
        "first_record": None,
        "precision": "day",
        "kind": "earliest_known",
        "spotify": "2019-03-01",
        "status": "partial",
        "source": "MusicBrainz, first-release-date of the recording, title and artist match checked",
        "url": "https://musicbrainz.org/search?query=Angel-Ho%20Like%20A%20Girl&type=recording",
        "checked": "2026-09-04",
        "note": "",
    },
    # ANOHNI — Drone Bomb Me
    "6JZfK4Z75nZm3VcZOVrpy0": {
        "first_public": "2016-03-09",
        "first_record": None,
        "precision": "day",
        "kind": "earliest_known",
        "spotify": "2016-05-06",
        "status": "partial",
        "source": "MusicBrainz, first-release-date of the recording, title and artist match checked",
        "url": "https://musicbrainz.org/search?query=ANOHNI%20Drone%20Bomb%20Me&type=recording",
        "checked": "2026-09-04",
        "note": "A compilation sits among the known releases.",
    },
    # ANOHNI — 4 DEGREES
    "3IDQXyHYuX2rdLnNfVzT3g": {
        "first_public": "2015-12-01",
        "first_record": None,
        "precision": "day",
        "kind": "earliest_known",
        "spotify": "2016-05-06",
        "status": "partial",
        "source": "MusicBrainz, first-release-date of the recording, title and artist match checked",
        "url": "https://musicbrainz.org/search?query=ANOHNI%204%20DEGREES&type=recording",
        "checked": "2026-09-04",
        "note": "A compilation sits among the known releases.",
    },
    # Sonja Sajzor — I Keep Doing This to Myself
    "6jiumfqTwOpXW6PDzsIBKl": {
        "first_public": "2018-11-14",
        "first_record": None,
        "precision": "day",
        "kind": "earliest_known",
        "spotify": "2018-11-14",
        "status": "partial",
        "source": "Spotify, track page metadata, read in session",
        "url": "https://open.spotify.com/",
        "checked": "2026-09-04",
        "note": "No entry in MusicBrainz or Discogs. Platform date, not corroborated. Album Prudence.",
    },
    # Lauren Auder, Celeste — Unseen (feat. Celeste)
    "2BQZhUPXdP9Nk1X84c7PtP": {
        "first_public": "2021-02-12",
        "first_record": None,
        "precision": "day",
        "kind": "earliest_known",
        "spotify": "2021-02-12",
        "status": "partial",
        "source": "MusicBrainz, first-release-date of the recording, title and artist match checked",
        "url": "https://musicbrainz.org/search?query=Lauren%20Auder%20Unseen%20%28feat.%20Celeste%29&type=recording",
        "checked": "2026-09-04",
        "note": "",
    },
    # Bülent Ersoy — Geceler  [pilote]
    "5e0ZXu358l51ckAZvai2Ef": {
        "first_public": 1980,
        "first_record": None,
        "precision": "year",
        "kind": "first",
        "spotify": "1988-08-04",
        "status": "verified",
        "source": "Discogs, release 7255550, Türküola EU-118 7-inch, B-side Geceler",
        "url": "https://www.discogs.com/release/7255550",
        "checked": "2026-09-04",
        "note": "Confirmed by MusicBrainz, single Beddua / Geceler, 1980. Spotify serves the 1988 album Biz Ayrılamayız. Whether it is the same recording is unknown, and makes no difference under the definition used here.",
    },
    # Bülent Ersoy — Ümit Hırsızı
    "0XIutL5epZuYV91bhCfFsR": {
        "first_public": "2019-03-22",
        "first_record": None,
        "precision": "day",
        "kind": "earliest_known",
        "spotify": "2019-03-22",
        "status": "partial",
        "source": "MusicBrainz, first-release-date of the recording, title and artist match checked",
        "url": "https://musicbrainz.org/search?query=B%C3%BClent%20Ersoy%20%C3%9Cmit%20H%C4%B1rs%C4%B1z%C4%B1&type=recording",
        "checked": "2026-09-04",
        "note": "",
    },
    # Antony and the Johnsons, ANOHNI — Hope There's Someone
    "1AHPsqF3EtHeWpOM06Y3Y4": {
        "first_public": 2005,
        "first_record": None,
        "precision": "year",
        "kind": "first",
        "spotify": "2005-02-07",
        "status": "verified",
        "source": "Discogs, album I Am A Bird Now, tracklist read",
        "url": "https://www.discogs.com/artist/68901",
        "checked": "2026-09-04",
        "note": "The compilation flag raised by the automated pass was a false positive: the original release is indeed from 2005.",
    },
    # Kim Petras — Heart to Break
    "1jFN0stMzLepoPxvPywGZj": {
        "first_public": "2018-02-14",
        "first_record": None,
        "precision": "day",
        "kind": "earliest_known",
        "spotify": "2018-02-14",
        "status": "partial",
        "source": "MusicBrainz, first-release-date of the recording, title and artist match checked",
        "url": "https://musicbrainz.org/search?query=Kim%20Petras%20Heart%20to%20Break&type=recording",
        "checked": "2026-09-04",
        "note": "A compilation sits among the known releases.",
    },
    # Kim Petras — Clarity
    "5pkemVhnBiIzMs2NLsXomQ": {
        "first_public": "2019-06-06",
        "first_record": None,
        "precision": "day",
        "kind": "earliest_known",
        "spotify": "2019-06-28",
        "status": "partial",
        "source": "MusicBrainz, first-release-date of the recording, title and artist match checked",
        "url": "https://musicbrainz.org/search?query=Kim%20Petras%20Clarity&type=recording",
        "checked": "2026-09-04",
        "note": "A compilation sits among the known releases.",
    },
    # Kim Petras — I Don't Want It At All
    "4xhYxKvAxtrRd83MiqOy29": {
        "first_public": "2017-08-01",
        "first_record": None,
        "precision": "day",
        "kind": "earliest_known",
        "spotify": "2017-08-01",
        "status": "partial",
        "source": "MusicBrainz, first-release-date of the recording, title and artist match checked",
        "url": "https://musicbrainz.org/search?query=Kim%20Petras%20I%20Don%27t%20Want%20It%20At%20All&type=recording",
        "checked": "2026-09-04",
        "note": "A compilation sits among the known releases.",
    },
    # Kim Petras — There Will Be Blood
    "75HFFq9W7Em0dTBG8QeGcT": {
        "first_public": "2019-10-01",
        "first_record": None,
        "precision": "day",
        "kind": "earliest_known",
        "spotify": "2020-10-23",
        "status": "partial",
        "source": "MusicBrainz, first-release-date of the recording, title and artist match checked",
        "url": "https://musicbrainz.org/search?query=Kim%20Petras%20There%20Will%20Be%20Blood&type=recording",
        "checked": "2026-09-04",
        "note": "A compilation sits among the known releases.",
    },
    # Kim Petras — Coconuts
    "71yN0yrHej3jhKXewbmtEh": {
        "first_public": "2021-12-03",
        "first_record": None,
        "precision": "day",
        "kind": "earliest_known",
        "spotify": "2021-12-03",
        "status": "partial",
        "source": "MusicBrainz, first-release-date of the recording, title and artist match checked",
        "url": "https://musicbrainz.org/search?query=Kim%20Petras%20Coconuts&type=recording",
        "checked": "2026-09-04",
        "note": "A compilation sits among the known releases.",
    },
    # Tone Sekelius — Girls & Dolls
    "6yAc1rz1RXRlYJac99xusK": {
        "first_public": "2026-06-10",
        "first_record": None,
        "precision": "day",
        "kind": "earliest_known",
        "spotify": "2026-06-10",
        "status": "partial",
        "source": "Spotify, track page metadata, read in session",
        "url": "https://open.spotify.com/",
        "checked": "2026-09-04",
        "note": "No entry in MusicBrainz or Discogs. Platform date, not corroborated.",
    },
    # Laura Les — Haunted
    "1toNKayLMeCcVlsLGXJl7n": {
        "first_public": "2020-11-13",
        "first_record": None,
        "precision": "day",
        "kind": "earliest_known",
        "spotify": "2021-03-12",
        "status": "partial",
        "source": "MusicBrainz, first-release-date of the recording, title and artist match checked",
        "url": "https://musicbrainz.org/search?query=Laura%20Les%20Haunted&type=recording",
        "checked": "2026-09-04",
        "note": "A compilation sits among the known releases.",
    },
    # femtanyl — P3T
    "1w0AFg23E67l57A3RMiXjC": {
        "first_public": "2023-07-03",
        "first_record": None,
        "precision": "day",
        "kind": "earliest_known",
        "spotify": "2023-07-03",
        "status": "partial",
        "source": "MusicBrainz, first-release-date of the recording, title and artist match checked",
        "url": "https://musicbrainz.org/search?query=femtanyl%20P3T&type=recording",
        "checked": "2026-09-04",
        "note": "A compilation sits among the known releases.",
    },
    # femtanyl — ACT RIGHT
    "2sVjF25Z4JTJxi9BXm5GtJ": {
        "first_public": "2023-06-05",
        "first_record": None,
        "precision": "day",
        "kind": "earliest_known",
        "spotify": "2023-07-10",
        "status": "partial",
        "source": "MusicBrainz, first-release-date of the recording, title and artist match checked",
        "url": "https://musicbrainz.org/search?query=femtanyl%20ACT%20RIGHT&type=recording",
        "checked": "2026-09-04",
        "note": "A compilation sits among the known releases.",
    },
    # femtanyl — GIRL HELL 1999  [pilote]
    "6XeW8fjwoAFQeQpYojPtVI": {
        "first_public": "2023-08-25",
        "first_record": None,
        "precision": "day",
        "kind": "first",
        "spotify": "2023-08-27",
        "status": "verified",
        "source": "SoundCloud, release_date field on the track; agrees with MusicBrainz",
        "url": "https://soundcloud.com/femtanyl/girl-hell-1999",
        "checked": "2026-09-04",
        "note": "The created_at field reads 2023-10-20, later than the release date: the file was re-uploaded. An upload timestamp alone is never a date.",
    },
    # femtanyl — KATAMARI
    "5iAE3uBqaZm9aHUx9yy6a0": {
        "first_public": "2023-08-13",
        "first_record": None,
        "precision": "day",
        "kind": "earliest_known",
        "spotify": "2023-08-13",
        "status": "partial",
        "source": "MusicBrainz, first-release-date of the recording, title and artist match checked",
        "url": "https://musicbrainz.org/search?query=femtanyl%20KATAMARI&type=recording",
        "checked": "2026-09-04",
        "note": "A compilation sits among the known releases.",
    },
    # femtanyl, ISSBROKIE — NASTYWERKKKK!
    "7kvQptbfqq5b4MWRQOMrZC": {
        "first_public": "2025-03-07",
        "first_record": None,
        "precision": "day",
        "kind": "earliest_known",
        "spotify": "2025-03-07",
        "status": "partial",
        "source": "MusicBrainz, first-release-date of the recording, title and artist match checked",
        "url": "https://musicbrainz.org/search?query=femtanyl%20NASTYWERKKKK%21&type=recording",
        "checked": "2026-09-04",
        "note": "A compilation sits among the known releases.",
    },
    # underscores — Spoiled little brat
    "724utiMbqUfT1g3tqbfQYu": {
        "first_public": "2021-03-25",
        "first_record": None,
        "precision": "day",
        "kind": "earliest_known",
        "spotify": "2021-03-25",
        "status": "partial",
        "source": "MusicBrainz, first-release-date of the recording, title and artist match checked",
        "url": "https://musicbrainz.org/search?query=underscores%20Spoiled%20little%20brat&type=recording",
        "checked": "2026-09-04",
        "note": "A compilation sits among the known releases.",
    },
    # underscores — Second hand embarrassment
    "1PEPcLm2QEo0HCRIhQjPq1": {
        "first_public": "2021-02-02",
        "first_record": None,
        "precision": "day",
        "kind": "earliest_known",
        "spotify": "2021-03-25",
        "status": "partial",
        "source": "MusicBrainz, first-release-date of the recording, title and artist match checked",
        "url": "https://musicbrainz.org/search?query=underscores%20Second%20hand%20embarrassment&type=recording",
        "checked": "2026-09-04",
        "note": "A compilation sits among the known releases.",
    },
    # underscores, 8485 — Your favorite sidekick
    "0VNjaRcmIowjLbPtYDhLuh": {
        "first_public": "2021-03-25",
        "first_record": None,
        "precision": "day",
        "kind": "earliest_known",
        "spotify": "2021-03-25",
        "status": "partial",
        "source": "MusicBrainz, first-release-date of the recording, title and artist match checked",
        "url": "https://musicbrainz.org/search?query=underscores%20Your%20favorite%20sidekick&type=recording",
        "checked": "2026-09-04",
        "note": "A compilation sits among the known releases.",
    },
    # underscores, gabby start — Locals (Girls like us) [with gabby start]
    "54n3iwz9mr7yxZi1EOX1Mz": {
        "first_public": "2023-07-12",
        "first_record": None,
        "precision": "day",
        "kind": "earliest_known",
        "spotify": "2024-06-28",
        "status": "partial",
        "source": "MusicBrainz, first-release-date of the recording, title and artist match checked",
        "url": "https://musicbrainz.org/search?query=underscores%20Locals%20%28Girls%20like%20us%29%20%5Bwith%20gabby%20start%5D&type=recording",
        "checked": "2026-09-04",
        "note": "A compilation sits among the known releases.",
    },
    # MONĀE, Cae Monāe — CISPHOBIC
    "5dIPCgTEDagbcs5QGmni8V": {
        "first_public": "2021-04-26",
        "first_record": None,
        "precision": "day",
        "kind": "earliest_known",
        "spotify": "2021-04-26",
        "status": "partial",
        "source": "Spotify, track page metadata, read in session",
        "url": "https://open.spotify.com/",
        "checked": "2026-09-04",
        "note": "No entry in MusicBrainz or Discogs. Platform date, not corroborated.",
    },
    # Petal Supply — Person - Angel Mix
    "5iTzaatezJzsUhX1QjT0Kp": {
        "first_public": "2023-06-09",
        "first_record": None,
        "precision": "day",
        "kind": "earliest_known",
        "spotify": "2024-01-26",
        "status": "partial",
        "source": "MusicBrainz, first-release-date of the recording, title and artist match checked",
        "url": "https://musicbrainz.org/search?query=Petal%20Supply%20Person%20-%20Angel%20Mix&type=recording",
        "checked": "2026-09-04",
        "note": "",
    },
    # Chase Icon — Like Me
    "51NYFGDXYKS4FkRqkw98hx": {
        "first_public": "2022-02-09",
        "first_record": None,
        "precision": "day",
        "kind": "earliest_known",
        "spotify": "2022-02-09",
        "status": "partial",
        "source": "MusicBrainz, first-release-date of the recording, title and artist match checked",
        "url": "https://musicbrainz.org/search?query=Chase%20Icon%20Like%20Me&type=recording",
        "checked": "2026-09-04",
        "note": "",
    },
    # Chase Icon — SRS
    "1d3hBkCcMvVzsZjaMiVvNs": {
        "first_public": "2021-01-15",
        "first_record": None,
        "precision": "day",
        "kind": "earliest_known",
        "spotify": "2021-01-15",
        "status": "partial",
        "source": "MusicBrainz, first-release-date of the recording, title and artist match checked",
        "url": "https://musicbrainz.org/search?query=Chase%20Icon%20SRS&type=recording",
        "checked": "2026-09-04",
        "note": "",
    },
    # Mel 4Ever — I Can't Quit
    "0Irj6PuEEGzi7JGJvAhdZ8": {
        "first_public": "2024-11-15",
        "first_record": None,
        "precision": "day",
        "kind": "earliest_known",
        "spotify": "2024-11-15",
        "status": "partial",
        "source": "MusicBrainz, first-release-date of the recording, title and artist match checked",
        "url": "https://musicbrainz.org/search?query=Mel%204Ever%20I%20Can%27t%20Quit&type=recording",
        "checked": "2026-09-04",
        "note": "",
    },
    # Mel 4Ever, Ayesha Erotica — Tongues
    "18QS9wnUr7DOhMb73monpK": {
        "first_public": "2024-01-19",
        "first_record": None,
        "precision": "day",
        "kind": "earliest_known",
        "spotify": "2024-01-19",
        "status": "partial",
        "source": "MusicBrainz, first-release-date of the recording, title and artist match checked",
        "url": "https://musicbrainz.org/search?query=Mel%204Ever%20Tongues&type=recording",
        "checked": "2026-09-04",
        "note": "",
    },
    # Stef Aranas — Cvnty
    "7EPHu29KqhsGk4dZAjM0o4": {
        "first_public": "2024-06-13",
        "first_record": None,
        "precision": "day",
        "kind": "earliest_known",
        "spotify": "2024-06-13",
        "status": "partial",
        "source": "Spotify, track page metadata, read in session",
        "url": "https://open.spotify.com/",
        "checked": "2026-09-04",
        "note": "No entry in MusicBrainz or Discogs. Platform date, not corroborated.",
    },
    # Ayesha Erotica — Vacation Bible School  [pilote]
    "1RXkdiCc4TtwPacmIKyUnX": {
        "first_public": 2018,
        "first_record": None,
        "precision": "year",
        "kind": "earliest_known",
        "spotify": "2018-12-31",
        "status": "partial",
        "source": "Ayeshapedia, entry for the track",
        "url": "https://ayeshaerotica.miraheze.org/wiki/Vacation_Bible_School",
        "checked": "2026-09-04",
        "note": "Three competing dates within 2018: 15 March per MusicBrainz, 25 September per the fan wiki, 31 December per Spotify. The original was deleted soon after and reposted in March 2024. A fan wiki is a tertiary source, so this stays partial.",
    },
    # Ayesha Erotica — Literal Legend
    "2gmwvGC1yOw8NdMcZE8nfo": {
        "first_public": "2017-08",
        "first_record": None,
        "precision": "month",
        "kind": "earliest_known",
        "spotify": "2017-10-25",
        "status": "partial",
        "source": "MusicBrainz, first-release-date of the recording, title and artist match checked",
        "url": "https://musicbrainz.org/search?query=Ayesha%20Erotica%20Literal%20Legend&type=recording",
        "checked": "2026-09-04",
        "note": "A compilation sits among the known releases.",
    },
    # Jane Remover — Dancing with your eyes closed
    "1XD4K4CGAKTIBmFpvuaFru": {
        "first_public": "2025-02-26",
        "first_record": None,
        "precision": "day",
        "kind": "earliest_known",
        "spotify": "2025-04-04",
        "status": "partial",
        "source": "MusicBrainz, first-release-date of the recording, title and artist match checked",
        "url": "https://musicbrainz.org/search?query=Jane%20Remover%20Dancing%20with%20your%20eyes%20closed&type=recording",
        "checked": "2026-09-04",
        "note": "",
    },
    # estelle allen — dui
    "3RLI8S7KpEZs4SqePGjM2R": {
        "first_public": "2022-10-21",
        "first_record": None,
        "precision": "day",
        "kind": "earliest_known",
        "spotify": "2023-01-13",
        "status": "partial",
        "source": "MusicBrainz, first-release-date of the recording, title and artist match checked",
        "url": "https://musicbrainz.org/search?query=estelle%20allen%20dui&type=recording",
        "checked": "2026-09-04",
        "note": "",
    },
    # osquinn — warm and fuzzy
    "7n7GrVTBmZMG4EULD5g0i3": {
        "first_public": "2022-07-22",
        "first_record": None,
        "precision": "day",
        "kind": "earliest_known",
        "spotify": "2022-07-22",
        "status": "partial",
        "source": "Spotify, track page metadata, read in session",
        "url": "https://open.spotify.com/",
        "checked": "2026-09-04",
        "note": "No entry in MusicBrainz or Discogs. Platform date, not corroborated.",
    },
    # Frost Children — Falling
    "6WkiWn8bf8S29wSk0VwK7h": {
        "first_public": "2025-07-01",
        "first_record": None,
        "precision": "day",
        "kind": "earliest_known",
        "spotify": "2025-09-12",
        "status": "partial",
        "source": "MusicBrainz, first-release-date of the recording, title and artist match checked",
        "url": "https://musicbrainz.org/search?query=Frost%20Children%20Falling&type=recording",
        "checked": "2026-09-04",
        "note": "A compilation sits among the known releases.",
    },
    # Frost Children, Kim Petras — RADIO (feat. Kim Petras)
    "06kFuqzhMk4E6IYeO0sTfx": {
        "first_public": "2025-09-12",
        "first_record": None,
        "precision": "day",
        "kind": "earliest_known",
        "spotify": "2025-09-12",
        "status": "partial",
        "source": "MusicBrainz, first-release-date of the recording, title and artist match checked",
        "url": "https://musicbrainz.org/search?query=Frost%20Children%20RADIO%20%28feat.%20Kim%20Petras%29&type=recording",
        "checked": "2026-09-04",
        "note": "",
    },
    # Villano Antillano — KLK
    "2Of9piZALXa4CC7Unxoeeg": {
        "first_public": "2022-07-14",
        "first_record": None,
        "precision": "day",
        "kind": "earliest_known",
        "spotify": "2022-07-14",
        "status": "partial",
        "source": "Spotify, track page metadata, read in session",
        "url": "https://open.spotify.com/",
        "checked": "2026-09-04",
        "note": "No entry in MusicBrainz or Discogs. Platform date, not corroborated.",
    },
    # Bizarrap, Villano Antillano — Villano Antillano: Bzrp Music Sessions, Vol.
    "4hceSKjrkDTO0nMKFcb3sj": {
        "first_public": "2022-06-08",
        "first_record": None,
        "precision": "day",
        "kind": "earliest_known",
        "spotify": "2022-06-08",
        "status": "partial",
        "source": "MusicBrainz, first-release-date of the recording, title and artist match checked",
        "url": "https://musicbrainz.org/search?query=Bizarrap%20Villano%20Antillano%3A%20Bzrp%20Music%20Sessions%2C%20Vol.%2051/66&type=recording",
        "checked": "2026-09-04",
        "note": "A compilation sits among the known releases.",
    },
    # Samantha Hudson, Villano Antillano — Full Lace y el Tuck
    "29Ga6IgetN8Xah85ZHZ8AC": {
        "first_public": "2025-04-03",
        "first_record": None,
        "precision": "day",
        "kind": "first",
        "spotify": "2025-05-23",
        "status": "verified",
        "source": "YouTube, official distribution channel, upload date; Subterfuge label announcement of 4 April 2025",
        "url": "https://www.youtube.com/watch?v=rcCfK7D5UsM",
        "checked": "2026-09-04",
        "note": "The May date belonged to the album Música Para Muñecas. The single precedes it by seven weeks.",
    },
    # Pupi Poisson, Arantxa Castilla-La Mancha, CA — Las Defectos
    "376mhFeloWqzQJQsqZpm9A": {
        "first_public": "2023-02-01",
        "first_record": None,
        "precision": "day",
        "kind": "earliest_known",
        "spotify": "2023-02-01",
        "status": "partial",
        "source": "MusicBrainz, first-release-date of the recording, title and artist match checked",
        "url": "https://musicbrainz.org/search?query=Pupi%20Poisson%20Las%20Defectos&type=recording",
        "checked": "2026-09-04",
        "note": "",
    },
    # Gad Yola — Travesti del Perú
    "78iHtTxYIK2mD6oL6lXqFF": {
        "first_public": 2024,
        "first_record": None,
        "precision": "year",
        "kind": "earliest_known",
        "spotify": "2024-06-21",
        "status": "partial",
        "source": "Discogs, track search, single result",
        "url": "https://www.discogs.com/",
        "checked": "2026-09-04",
        "note": "Absent from MusicBrainz. A single Discogs result, not corroborated.",
    },
    # JEDET — VENENO PA' TU PIEL
    "5PMtJGEDIO0eIToF0YRUQ5": {
        "first_public": "2022-10-14",
        "first_record": None,
        "precision": "day",
        "kind": "earliest_known",
        "spotify": "2022-10-14",
        "status": "partial",
        "source": "Spotify, track page metadata, read in session",
        "url": "https://open.spotify.com/",
        "checked": "2026-09-04",
        "note": "No entry in MusicBrainz or Discogs. Platform date, not corroborated. Album A LOS HOMBRES QUE HE TENIDO QUE OLVIDAR.",
    },
    # Umlilo — Zulu Lami
    "2KryklrVDGmWL8IvoGNbb5": {
        "first_public": "2026-07-23",
        "first_record": None,
        "precision": "day",
        "kind": "first",
        "spotify": "2026-07-23",
        "status": "verified",
        "source": "Apple Music, artist discography, Zulu Lami - Single dated 23 July 2026; agrees with Spotify",
        "url": "https://music.apple.com/us/artist/umlilo/883878326",
        "checked": "2026-09-04",
        "note": "A late date looked at first like a reissue, on the false premise that Umlilo stopped releasing around 2016. The discography shows continuous activity: Friday To Sunday (2018), Mpumi (2023), then Digital Twin, Always on my mind and Cynthesia in 2025, Vuka Zulu and Umvuko in 2026, on their own label Future Kwaai Records. Zulu Lami is a new single from that run, not a reissue. Absent from the Bandcamp tracklists of Shades of Kwaai and Aluta, both November 2016, read in session.",
    },
    # Titica, Ary — Olha o Boneco  [pilote]
    "1YsFdaP9QG9NhjYS3o0g5P": {
        "first_public": "2011-10-15",
        "first_record": None,
        "precision": "day",
        "kind": "first",
        "spotify": "2011-10-15",
        "status": "verified",
        "source": "Portuguese Wikipedia, album Chão..., seventh track",
        "url": "https://pt.wikipedia.org/wiki/Ch%C3%A3o..._(%C3%A1lbum)",
        "checked": "2026-09-04",
        "note": "The single came after the album, on 17 February 2012. Spotify is right here.",
    },
    # Titica, Kelmer Pastilha, Mauro Xtraga — Olha a Banana
    "5lz6U9dCYBmEY6oLrW22VE": {
        "first_public": "2022-12-02",
        "first_record": None,
        "precision": "day",
        "kind": "earliest_known",
        "spotify": "2022-12-02",
        "status": "partial",
        "source": "MusicBrainz, first-release-date of the recording, title and artist match checked",
        "url": "https://musicbrainz.org/search?query=Titica%20Olha%20a%20Banana&type=recording",
        "checked": "2026-09-04",
        "note": "",
    },
    # Against Me! — True Trans Soul Rebel
    "0a0CwJBn8lmT5ifk63EUbP": {
        "first_public": "2012-05-30",
        "first_record": None,
        "precision": "day",
        "kind": "first",
        "spotify": "2014-01-21",
        "status": "partial",
        "source": "Songfacts, entry for the song",
        "url": "https://www.songfacts.com/facts/against-me/true-trans-soul-rebel",
        "checked": "2026-09-04",
        "note": "First public performance at the Ogden Theatre, Denver, on 30 May 2012, nineteen months before the album. A tertiary source, but a precise one, hence partial.",
    },
    # Against Me! — Transgender Dysphoria Blues
    "4b1Y41U44kP7gzO7MUNGbe": {
        "first_public": "2014-01-21",
        "first_record": None,
        "precision": "day",
        "kind": "first",
        "spotify": "2014-01-21",
        "status": "verified",
        "source": "Discogs, album Transgender Dysphoria Blues, tracklist read; agrees with MusicBrainz",
        "url": "https://www.discogs.com/artist/25196",
        "checked": "2026-09-04",
        "note": "Compilation flag from the automated pass, lifted.",
    },
    # Against Me! — The Ocean
    "14uL43Gg4ujizaATehrryk": {
        "first_public": 2007,
        "first_record": None,
        "precision": "year",
        "kind": "first",
        "spotify": "2007-07-09",
        "status": "verified",
        "source": "Discogs, album New Wave, tracklist read; agrees with MusicBrainz",
        "url": "https://www.discogs.com/artist/25196",
        "checked": "2026-09-04",
        "note": "Compilation flag from the automated pass, lifted.",
    },
    # Against Me! — Black Me Out
    "0wIpjjcXFgGtJUmBIRAAju": {
        "first_public": "2014-01-21",
        "first_record": None,
        "precision": "day",
        "kind": "first",
        "spotify": "2014-01-21",
        "status": "verified",
        "source": "Discogs, album Transgender Dysphoria Blues, tracklist read; agrees with MusicBrainz",
        "url": "https://www.discogs.com/artist/25196",
        "checked": "2026-09-04",
        "note": "Compilation flag from the automated pass, lifted.",
    },
    # Anita Velveeta — T4T
    "2DUAIlPmzV2is5OQIZASUA": {
        "first_public": "2022-01-04",
        "first_record": None,
        "precision": "day",
        "kind": "earliest_known",
        "spotify": "2022-01-04",
        "status": "partial",
        "source": "MusicBrainz, first-release-date of the recording, title and artist match checked",
        "url": "https://musicbrainz.org/search?query=Anita%20Velveeta%20T4T&type=recording",
        "checked": "2026-09-04",
        "note": "",
    },
    # Ezra Furman — Restless Year
    "7yeRNInEt2DOFYW0BkETEe": {
        "first_public": "2015-05-14",
        "first_record": None,
        "precision": "day",
        "kind": "earliest_known",
        "spotify": "2015-06-15",
        "status": "partial",
        "source": "MusicBrainz, first-release-date of the recording, title and artist match checked",
        "url": "https://musicbrainz.org/search?query=Ezra%20Furman%20Restless%20Year&type=recording",
        "checked": "2026-09-04",
        "note": "A compilation sits among the known releases.",
    },
    # G.L.O.S.S. — Targets of Men Targets of Men
    "4NYRtDYROQW2D2ctcylcri": {
        "first_public": "2015-01-16",
        "first_record": None,
        "precision": "day",
        "kind": "earliest_known",
        "spotify": "2016-06-24",
        "status": "partial",
        "source": "MusicBrainz, first-release-date of the recording, title and artist match checked",
        "url": "https://musicbrainz.org/search?query=G.L.O.S.S.%20Targets%20of%20Men%20Targets%20of%20Men&type=recording",
        "checked": "2026-09-04",
        "note": "A compilation sits among the known releases.",
    },
    # Changeline — OCTOPUS.LADY
    "3bnvoYUrPkgh0E3ZeYZ3me": {
        "first_public": "2023-01-25",
        "first_record": None,
        "precision": "day",
        "kind": "earliest_known",
        "spotify": "2023-01-25",
        "status": "partial",
        "source": "MusicBrainz, first-release-date of the recording, title and artist match checked",
        "url": "https://musicbrainz.org/search?query=Changeline%20OCTOPUS.LADY&type=recording",
        "checked": "2026-09-04",
        "note": "",
    },
    # Changeline, Stolas — ANARCONNASSE
    "20JYh6XUjLjiN1CyJ32ZiY": {
        "first_public": "2023-04-28",
        "first_record": None,
        "precision": "day",
        "kind": "earliest_known",
        "spotify": "2023-04-28",
        "status": "partial",
        "source": "MusicBrainz, first-release-date of the recording, title and artist match checked",
        "url": "https://musicbrainz.org/search?query=Changeline%20ANARCONNASSE&type=recording",
        "checked": "2026-09-04",
        "note": "",
    },
    # Changeline — JE.DÉTESTE.LA.FRANCE.pt1 (il y aura pas de p
    "7lc4ue2LiSfYRaABxq4YkT": {
        "first_public": "2025-11-05",
        "first_record": None,
        "precision": "day",
        "kind": "earliest_known",
        "spotify": "2025-11-05",
        "status": "partial",
        "source": "MusicBrainz, first-release-date of the recording, title and artist match checked",
        "url": "https://musicbrainz.org/search?query=Changeline%20JE.D%C3%89TESTE.LA.FRANCE.pt1%20%28il%20y%20aura%20pas%20de%20pt2%29&type=recording",
        "checked": "2026-09-04",
        "note": "",
    },
    # THÉA — CAVALE! CAVALE!
    "0ZQLRkRyn3300WyapdPoWT": {
        "first_public": "2024-11-06",
        "first_record": None,
        "precision": "day",
        "kind": "earliest_known",
        "spotify": "2024-11-06",
        "status": "partial",
        "source": "MusicBrainz, first-release-date of the recording, title and artist match checked",
        "url": "https://musicbrainz.org/search?query=TH%C3%89A%20CAVALE%21%20CAVALE%21&type=recording",
        "checked": "2026-09-04",
        "note": "",
    },
    # THÉA — JUSTE AMIS
    "3RXajeZOzqXWrQwLDfTzKK": {
        "first_public": "2023-11-17",
        "first_record": None,
        "precision": "day",
        "kind": "earliest_known",
        "spotify": "2023-11-17",
        "status": "partial",
        "source": "MusicBrainz, first-release-date of the recording, title and artist match checked",
        "url": "https://musicbrainz.org/search?query=TH%C3%89A%20JUSTE%20AMIS&type=recording",
        "checked": "2026-09-04",
        "note": "",
    },
    # THÉA — Guillotine
    "0bWpWsvZeTTNLQ9nuXqKIN": {
        "first_public": "2021-04-19",
        "first_record": None,
        "precision": "day",
        "kind": "earliest_known",
        "spotify": "2023-02-10",
        "status": "partial",
        "source": "MusicBrainz, first-release-date of the recording, title and artist match checked",
        "url": "https://musicbrainz.org/search?query=TH%C3%89A%20Guillotine&type=recording",
        "checked": "2026-09-04",
        "note": "",
    },
    # THÉA — ANXIOLYTIQUES
    "7zBUh6s2Ca8eAURfnVHCTS": {
        "first_public": "2023-11-17",
        "first_record": None,
        "precision": "day",
        "kind": "earliest_known",
        "spotify": "2023-10-18",
        "status": "partial",
        "source": "MusicBrainz, first-release-date of the recording, title and artist match checked",
        "url": "https://musicbrainz.org/search?query=TH%C3%89A%20ANXIOLYTIQUES&type=recording",
        "checked": "2026-09-04",
        "note": "",
    },
    # Laura Jane Grace — The Best Ever Death Metal Band in Denton
    "3ShIGvHRm0q9iIDowUMjls": {
        "first_public": "2017-09-28",
        "first_record": None,
        "precision": "day",
        "kind": "earliest_known",
        "spotify": "2017-09-28",
        "status": "partial",
        "source": "MusicBrainz, first-release-date of the recording, title and artist match checked",
        "url": "https://musicbrainz.org/search?query=Laura%20Jane%20Grace%20The%20Best%20Ever%20Death%20Metal%20Band%20in%20Denton&type=recording",
        "checked": "2026-09-04",
        "note": "A compilation sits among the known releases.",
    },
    # Jayne County — Man Enough To Be A Woman
    "1IF61ped0XehHvw2CFXP3B": {
        "first_public": 1978,
        "first_record": None,
        "precision": "year",
        "kind": "first",
        "spotify": "1987-01-01",
        "status": "verified",
        "source": "Discogs, release 2870540, Attic LAT 1064 LP, tracklist read (side B, track 1)",
        "url": "https://www.discogs.com/release/2870540-Wayne-County-The-Electric-Chairs-Man-Enough-To-Be-A-Woman",
        "checked": "2026-09-04",
        "note": "The 1986 album this entry first relied on is a compilation; the song first appeared on a 1978 LP, whose tracklist was read on Discogs. An eight-year correction, found by cross-checking and confirmed at the source.",
    },
    # Marie France, Chrissie Hynde — Un garçon qui pleure
    "0VhGzYfT2ZOFz31b5IH7yJ": {
        "first_public": "2012-04-09",
        "first_record": None,
        "precision": "day",
        "kind": "earliest_known",
        "spotify": "2012-01-01",
        "status": "partial",
        "source": "MusicBrainz, first-release-date of the recording, title and artist match checked",
        "url": "https://musicbrainz.org/search?query=Marie%20France%20Un%20gar%C3%A7on%20qui%20pleure&type=recording",
        "checked": "2026-09-04",
        "note": "A proposed date of 2009 rested on a fan site page. The page was opened and mentions neither this duet nor the album Kiss. The correction was not kept.",
    },
    # Venus de Mars and All the Pretty Horses — Boys
    "3zGmkzXqXsXYVlGzJFpgCW": {
        "first_public": "2002-12-17",
        "first_record": None,
        "precision": "day",
        "kind": "first",
        "spotify": "2023-08-08",
        "status": "verified",
        "source": "Bandcamp, page for CREATURE (remastered 2023), which dates the original release",
        "url": "https://venusdemars.bandcamp.com/album/creature-remastered-2023",
        "checked": "2026-09-04",
        "note": "The page states that CREATURE was first released on 17 December 2002. Spotify serves the 2023 remaster, where the song is listed as Boys/Revolution. A gap of 21 years.",
    },
    # Venus de Mars and All the Pretty Horses — White Horses
    "7GAI6zWpmst6dSfu1wIA1O": {
        "first_public": "2002-12-17",
        "first_record": None,
        "precision": "day",
        "kind": "earliest_known",
        "spotify": "2023-08-08",
        "status": "partial",
        "source": "MusicBrainz, first-release-date of the recording, title and artist match checked",
        "url": "https://musicbrainz.org/search?query=Venus%20de%20Mars%20and%20All%20the%20Pretty%20Horses%20White%20Horses&type=recording",
        "checked": "2026-09-04",
        "note": "",
    },
    # Venus De Mars — Take My Shoulder (feat. Laura Jane Grace)
    "3Vk1AHIh1CoiQzFroldMhO": {
        "first_public": "2015-04-07",
        "first_record": None,
        "precision": "day",
        "kind": "earliest_known",
        "spotify": "2015-04-07",
        "status": "partial",
        "source": "Spotify metadata read in session; MusicBrainz gave 2017",
        "url": "https://open.spotify.com/",
        "checked": "2026-09-04",
        "note": "Once the platform column was filled in, it turned out to be earlier than the MusicBrainz date. The earlier of the two is kept.",
    },
    # Tingtongketz — Berubah
    "2inX5xyazBvcZYLx3wRBwh": {
        "first_public": "2019-07-22",
        "first_record": None,
        "precision": "day",
        "kind": "earliest_known",
        "spotify": "2019-07-22",
        "status": "partial",
        "source": "Spotify, track page metadata, read in session",
        "url": "https://open.spotify.com/",
        "checked": "2026-09-04",
        "note": "No entry in MusicBrainz or Discogs. Platform date, not corroborated. Album Enjoy the Monsoon.",
    },
    # Beth Elliott — Lady on the Subway
    "73xUwV4DkcelY7seMyY0PY": {
        "first_public": 1976,
        "first_record": None,
        "precision": "year",
        "kind": "earliest_known",
        "spotify": "2005-01-01",
        "status": "partial",
        "source": "Queer Music Heritage, script and playlist of JD Doyle's June 2007 programme; Julia Golda Harris, Signs 51(1), 2025",
        "url": "https://www.queermusicheritage.com/jun2007s.html",
        "checked": "2026-09-04",
        "note": "Queer Music Heritage states, word for word, “That was ‘Lady on the Subway,’ written in 1970 and recorded in 1976”, and introduces it as “a song she wrote in 1970, which you may know was before Olivia Records ever dreamed of a woman-loving-woman song”. Elliott said it was her way of getting to hear a girl group love song addressed from one woman to another, after the Murmaids’ Popsicles, Icicles. The date held is 1976, the recording year, as a ceiling: Julia Golda Harris (Signs, 2025) describes this repertoire as written for live performance by artists without studio access, so a song written in 1970 by a musician playing Bay Area coffee houses was almost certainly heard long before it was taped. No source dates a performance. Spotify serves the 2005 CD Buried Treasure, twenty-nine years later.",
    },
    # Beth Elliott — Ballad of the Oklahoma Women's Liberation Fr  [pilote]
    "4dtyeDMnVKKo89QbbDtD5M": {
        "first_public": 1976,
        "first_record": None,
        "precision": "year",
        "kind": "earliest_known",
        "spotify": "2005-01-01",
        "status": "partial",
        "source": "Queer Music Heritage for the recording year; Julia Golda Harris, Womanly Sounds, Signs 51(1), 2025, for the songs' live life",
        "url": "https://doi.org/10.1086/736001",
        "checked": "2026-09-04",
        "note": "Written as a retort to Tammy Wynette’s “Stand by Your Man” (1968). Julia Golda Harris, writing in Signs in 2025 after interviewing Elliott, names it among “her early popular tunes” and describes these songs as works made for live performance, because artists of that scene “largely lacked access to recording studios”. A contemporaneous account of the 1973 West Coast Lesbian Conference in The Lesbian Tide records that Elliott had “written some far-out feminist songs” and that this was why she was there; no source names which songs she sang, since the stage performances were not recorded. The date held is 1976, the year Queer Music Heritage gives for the recording, and it is a ceiling rather than a first: the song was heard in rooms before it was ever committed to tape. Harris mentions no 1976 record at all, describing the songs instead as “later recorded for a 2005 album”, which leaves the LP asserted by a Wikipedia footnote unknown to the scholarship and to every catalogue.",
    },
    # Namoli Brennet — Boy in a Dress
    "02L1ngagXNRt8W3Flbe9Sw": {
        "first_public": 2002,
        "first_record": None,
        "precision": "year",
        "kind": "first",
        "spotify": "2002-01-01",
        "status": "verified",
        "source": "Discogs, album Boy In A Dress, tracklist read",
        "url": "https://www.discogs.com/artist/2404269",
        "checked": "2026-09-04",
        "note": "Absent from MusicBrainz. The album carries the song's name.",
    },
    # Mya Byrne — Where the Lavender Grows
    "7KtbrK74NNA4ySRZ49DC7R": {
        "first_public": "2022-05-13",
        "first_record": None,
        "precision": "day",
        "kind": "earliest_known",
        "spotify": "2022-05-13",
        "status": "partial",
        "source": "Spotify, track page metadata, read in session",
        "url": "https://open.spotify.com/",
        "checked": "2026-09-04",
        "note": "No entry in MusicBrainz or Discogs. Platform date, not corroborated. Replaces a false MusicBrainz match that gave 2021-09-05.",
    },
    # Left at London — Revolution Lover
    "3qBg6BeHJlGgwl5aCa09EC": {
        "first_public": "2018-11-09",
        "first_record": None,
        "precision": "day",
        "kind": "earliest_known",
        "spotify": "2018-11-10",
        "status": "partial",
        "source": "MusicBrainz, first-release-date of the recording, title and artist match checked",
        "url": "https://musicbrainz.org/search?query=Left%20at%20London%20Revolution%20Lover&type=recording",
        "checked": "2026-09-04",
        "note": "A compilation sits among the known releases.",
    },
    # Left at London — 6 Feet
    "3z4KIXgkhLauhNP3ubB8cF": {
        "first_public": "2019-12-04",
        "first_record": None,
        "precision": "day",
        "kind": "earliest_known",
        "spotify": "2025-06-06",
        "status": "partial",
        "source": "MusicBrainz, first-release-date of the recording, title and artist match checked",
        "url": "https://musicbrainz.org/search?query=Left%20at%20London%206%20Feet&type=recording",
        "checked": "2026-09-04",
        "note": "A compilation sits among the known releases.",
    },
    # June Jones, Geryon — Motorcycle
    "2CznvTOsuLh0USpHJqEc6V": {
        "first_public": "2021-07-28",
        "first_record": None,
        "precision": "day",
        "kind": "earliest_known",
        "spotify": "2021-07-28",
        "status": "partial",
        "source": "Spotify metadata read in session; MusicBrainz gave 2022-09-23",
        "url": "https://open.spotify.com/",
        "checked": "2026-09-04",
        "note": "The platform column turned out to be earlier than the MusicBrainz date. The earlier of the two is kept.",
    },
    # jasmine.4.t — Skin On Skin
    "2jFP4mAHcDmGe7DEKKLyJa": {
        "first_public": "2024-07-18",
        "first_record": None,
        "precision": "day",
        "kind": "earliest_known",
        "spotify": "2025-01-17",
        "status": "partial",
        "source": "MusicBrainz, first-release-date of the recording, title and artist match checked",
        "url": "https://musicbrainz.org/search?query=jasmine.4.t%20Skin%20On%20Skin&type=recording",
        "checked": "2026-09-04",
        "note": "",
    },
    # Vivek Shraya — I Take All the Blame
    "0kNjtDBxrpjJTZn9w5Eq3C": {
        "first_public": "2017-10-20",
        "first_record": None,
        "precision": "day",
        "kind": "earliest_known",
        "spotify": "2017-10-20",
        "status": "partial",
        "source": "MusicBrainz, first-release-date of the recording, title and artist match checked",
        "url": "https://musicbrainz.org/search?query=Vivek%20Shraya%20I%20Take%20All%20the%20Blame&type=recording",
        "checked": "2026-09-04",
        "note": "A compilation sits among the known releases.",
    },
    # Vivek Shraya, Queer Songbook Orchestra — Part-Time Woman
    "2fB0l9upVjg0QTeMyrIVtc": {
        "first_public": "2017-06-09",
        "first_record": None,
        "precision": "day",
        "kind": "earliest_known",
        "spotify": "2017-06-09",
        "status": "partial",
        "source": "MusicBrainz, first-release-date of the recording, title and artist match checked",
        "url": "https://musicbrainz.org/search?query=Vivek%20Shraya%20Part-Time%20Woman&type=recording",
        "checked": "2026-09-04",
        "note": "",
    },
    # Luisa Almaguer — Exiliades
    "5nnBHHzUDOGvdMBiXofB00": {
        "first_public": "2018-02-21",
        "first_record": None,
        "precision": "day",
        "kind": "earliest_known",
        "spotify": "2019-02-22",
        "status": "partial",
        "source": "MusicBrainz, first-release-date of the recording, title and artist match checked",
        "url": "https://musicbrainz.org/search?query=Luisa%20Almaguer%20Exiliades&type=recording",
        "checked": "2026-09-04",
        "note": "",
    },
    # Luisa Almaguer — Mataronomatar
    "6JGJdnIbq4UqKgzFaOIXwE": {
        "first_public": "2019-01-01",
        "first_record": None,
        "precision": "day",
        "kind": "earliest_known",
        "spotify": "2019-02-22",
        "status": "partial",
        "source": "MusicBrainz, first-release-date of the recording, title and artist match checked",
        "url": "https://musicbrainz.org/search?query=Luisa%20Almaguer%20Mataronomatar&type=recording",
        "checked": "2026-09-04",
        "note": "",
    },
    # Susy Shock — Vidalita, Vidalita
    "3nxFYWNFG2qGYEuhEzomtO": {
        "first_public": "2014-05-02",
        "first_record": None,
        "precision": "day",
        "kind": "earliest_known",
        "spotify": "2014-05-02",
        "status": "partial",
        "source": "Spotify metadata read in session; year agrees with the Discogs discography",
        "url": "https://open.spotify.com/",
        "checked": "2026-09-04",
        "note": "Album Buena Vida y Poca Vergüenza, also dated 2014 on Discogs.",
    },
    # La Bruja de Texcoco — Té de Malvón
    "3BYSoeWlqUgIwfY77C8VgE": {
        "first_public": "2019-03-21",
        "first_record": None,
        "precision": "day",
        "kind": "earliest_known",
        "spotify": "2019-04-12",
        "status": "partial",
        "source": "MusicBrainz, first-release-date of the recording, title and artist match checked",
        "url": "https://musicbrainz.org/search?query=La%20Bruja%20de%20Texcoco%20T%C3%A9%20de%20Malv%C3%B3n&type=recording",
        "checked": "2026-09-04",
        "note": "",
    },
    # La Bruja de Texcoco — Laabe Muxhe
    "1QrL7ucS71Ih4HXBOsuajv": {
        "first_public": "2019-03-21",
        "first_record": None,
        "precision": "day",
        "kind": "earliest_known",
        "spotify": "2019-04-12",
        "status": "partial",
        "source": "MusicBrainz, first-release-date of the recording, title and artist match checked",
        "url": "https://musicbrainz.org/search?query=La%20Bruja%20de%20Texcoco%20Laabe%20Muxhe&type=recording",
        "checked": "2026-09-04",
        "note": "",
    },
    # Ethel Cain — American Teenager
    "4ltqfN12ohaVZdM6C45gMg": {
        "first_public": "2022-04-21",
        "first_record": None,
        "precision": "day",
        "kind": "earliest_known",
        "spotify": "2022-05-12",
        "status": "partial",
        "source": "MusicBrainz, first-release-date of the recording, title and artist match checked",
        "url": "https://musicbrainz.org/search?query=Ethel%20Cain%20American%20Teenager&type=recording",
        "checked": "2026-09-04",
        "note": "A compilation sits among the known releases.",
    },
    # Steam Powered Giraffe — Honeybee
    "3MZjOGeXhpHbQ9ESMNFFnH": {
        "first_public": "2012-05-23",
        "first_record": None,
        "precision": "day",
        "kind": "earliest_known",
        "spotify": "2012-05-23",
        "status": "partial",
        "source": "Spotify and Discogs, album The 2 Cent Show, Discogs tracklist read",
        "url": "https://www.discogs.com/artist/3211940",
        "checked": "2026-09-04",
        "note": "Two sources agree on 2012. MusicBrainz offers 2011-02-01, though the song is not on the Discogs tracklist of the 2011 live album. The divergence is flagged, not settled.",
    },
    # SuperKnova — Serotonin Serenade
    "2Ff6Ghw8TRJGuAbJamtt4X": {
        "first_public": "2019-05-27",
        "first_record": None,
        "precision": "day",
        "kind": "earliest_known",
        "spotify": "2019-07-29",
        "status": "partial",
        "source": "MusicBrainz, first-release-date of the recording, title and artist match checked",
        "url": "https://musicbrainz.org/search?query=SuperKnova%20Serotonin%20Serenade&type=recording",
        "checked": "2026-09-04",
        "note": "",
    },
    # Daniela Vega — Ombra Mai Fu
    "1ovz0bZeO5YTBQTXIFf5Am": {
        "first_public": "2018-01-05",
        "first_record": None,
        "precision": "day",
        "kind": "earliest_known",
        "spotify": "2018-01-01",
        "status": "partial",
        "source": "MusicBrainz, first-release-date of the recording, title and artist match checked",
        "url": "https://musicbrainz.org/search?query=Daniela%20Vega%20Ombra%20Mai%20Fu&type=recording",
        "checked": "2026-09-04",
        "note": "A compilation sits among the known releases.",
    },
    # Daniela Vega — Sposa Son Disprezzata
    "5P9EKJfOZtuwtTR5C5362i": {
        "first_public": "2018-01-05",
        "first_record": None,
        "precision": "day",
        "kind": "earliest_known",
        "spotify": "2018-01-01",
        "status": "partial",
        "source": "MusicBrainz, first-release-date of the recording, title and artist match checked",
        "url": "https://musicbrainz.org/search?query=Daniela%20Vega%20Sposa%20Son%20Disprezzata&type=recording",
        "checked": "2026-09-04",
        "note": "A compilation sits among the known releases.",
    },
    # Tona Brown, Geraldine Boone — I, Too  [pilote]
    "1OpCGPKSq4IfpvLptsSMR9": {
        "first_public": 2012,
        "first_record": None,
        "precision": "year",
        "kind": "first",
        "spotify": "2012-07-05",
        "status": "verified",
        "source": "MusicBrainz, first-release-date 2012-07-12, album This Is Who I Am",
        "url": "https://musicbrainz.org/search?query=Tona+Brown+I%2C+Too&type=recording",
        "checked": "2026-09-04",
        "note": "The two sources differ by seven days, hence a date given to the year. Langston Hughes's poem and Margaret Bonds's setting are older; they are not what is being dated here.",
    },
    # Tona Brown, Geraldine Boone — Dream Variations
    "5l2zYkyTXtYa8xk965ofqD": {
        "first_public": "2012-07-12",
        "first_record": None,
        "precision": "day",
        "kind": "earliest_known",
        "spotify": "2012-07-05",
        "status": "partial",
        "source": "MusicBrainz, first-release-date of the recording, title and artist match checked",
        "url": "https://musicbrainz.org/search?query=Tona%20Brown%20Dream%20Variations&type=recording",
        "checked": "2026-09-04",
        "note": "",
    },
    # Jackie Shane — Any Other Way  [pilote]
    "5dtUOwEmnDAzsdodWJk4DA": {
        "first_public": 1963,
        "first_record": 1962,
        "precision": "year",
        "kind": "first",
        "spotify": "1963-01-01",
        "status": "verified",
        "source": "MusicBrainz, first-release-date of the recording, single Any Other Way / Sticks and Stones",
        "url": "https://musicbrainz.org/search?query=Jackie+Shane+Any+Other+Way&type=recording",
        "checked": "2026-09-04",
        "note": "MusicBrainz also carries a 1967 live version and the 2017 Numero compilation. Spotify does serve the single. Recorded in Boston in 1962, released in 1963: a documented one-year gap.",
    },
    # Veronica Klaus — I Will Survive
    "5NnQ2xIeHDKc1B19rxfcV3": {
        "first_public": 2005,
        "first_record": None,
        "precision": "year",
        "kind": "first",
        "spotify": "2005-01-01",
        "status": "verified",
        "source": "Discogs, album Live At The Lodge, tracklist read",
        "url": "https://www.discogs.com/artist/2154243",
        "checked": "2026-09-04",
        "note": "Replaces a false MusicBrainz match that returned I Will Follow Him by Klaus Wunderlich, 1973.",
    },
    # Jinkx Monsoon — Just Me (The Gender Binary Blues)
    "56xBg5e9rfrFqcqa4llUw7": {
        "first_public": "2018-01-12",
        "first_record": None,
        "precision": "day",
        "kind": "earliest_known",
        "spotify": "2018-01-12",
        "status": "partial",
        "source": "MusicBrainz, first-release-date of the recording, title and artist match checked",
        "url": "https://musicbrainz.org/search?query=Jinkx%20Monsoon%20Just%20Me%20%28The%20Gender%20Binary%20Blues%29&type=recording",
        "checked": "2026-09-04",
        "note": "",
    },
    # Shea Diamond — I Am Her
    "5WttRLHcZHhaIii5KwKh3Y": {
        "first_public": "2016-11-01",
        "first_record": None,
        "precision": "day",
        "kind": "earliest_known",
        "spotify": "2016-10-07",
        "status": "partial",
        "source": "MusicBrainz, first-release-date of the recording, title and artist match checked",
        "url": "https://musicbrainz.org/search?query=Shea%20Diamond%20I%20Am%20Her&type=recording",
        "checked": "2026-09-04",
        "note": "",
    },
    # Shea Diamond — Keisha Complexion
    "0gm0OruZdJlu8jamJe5OCh": {
        "first_public": "2018-04-27",
        "first_record": None,
        "precision": "day",
        "kind": "earliest_known",
        "spotify": "2018-04-27",
        "status": "partial",
        "source": "MusicBrainz, first-release-date of the recording, title and artist match checked",
        "url": "https://musicbrainz.org/search?query=Shea%20Diamond%20Keisha%20Complexion&type=recording",
        "checked": "2026-09-04",
        "note": "",
    },
    # Mila Jam — Bruised
    "3BqWvhPear6eKPwhwJRFpO": {
        "first_public": "2018-10-04",
        "first_record": None,
        "precision": "day",
        "kind": "earliest_known",
        "spotify": "2018-10-04",
        "status": "partial",
        "source": "Spotify, track page metadata, read in session",
        "url": "https://open.spotify.com/",
        "checked": "2026-09-04",
        "note": "No entry in MusicBrainz or Discogs. Platform date, not corroborated. Replaces a false MusicBrainz match.",
    },
    # Mila Jam — Faces
    "7luHAaHXty1Nl3AcscZIDT": {
        "first_public": "2017-03-15",
        "first_record": None,
        "precision": "day",
        "kind": "earliest_known",
        "spotify": "2017-03-15",
        "status": "partial",
        "source": "Spotify, track page metadata, read in session",
        "url": "https://open.spotify.com/",
        "checked": "2026-09-04",
        "note": "No entry in MusicBrainz or Discogs. Platform date, not corroborated. Self-titled single. Replaces a false MusicBrainz match.",
    },
    # Peppermint — Best Sex
    "2qpx5shtNEO1DuK8iEoJoB": {
        "first_public": "2020-10-02",
        "first_record": None,
        "precision": "day",
        "kind": "earliest_known",
        "spotify": "2020-10-02",
        "status": "partial",
        "source": "Spotify, track page metadata, read in session",
        "url": "https://open.spotify.com/",
        "checked": "2026-09-04",
        "note": "No entry in MusicBrainz or Discogs. Platform date, not corroborated. Album A Girl Like Me: Letters To My Lovers.",
    },
    # Peppermint — A Girl Like Me
    "3ApVA7ID6PkS0fGzNF4mFw": {
        "first_public": "2020-10-16",
        "first_record": None,
        "precision": "day",
        "kind": "earliest_known",
        "spotify": "2020-10-16",
        "status": "partial",
        "source": "Spotify, track page metadata, read in session",
        "url": "https://open.spotify.com/",
        "checked": "2026-09-04",
        "note": "No entry in MusicBrainz or Discogs. Platform date, not corroborated. Replaces a false MusicBrainz match that returned Got a Big Fine Girl by Peppermint Harris, 1962.",
    },
    # Ah-Mer-Ah-Su — Heartbreaker
    "4ED8r6i90zmUG4kfbiVoou": {
        "first_public": "2018-07-27",
        "first_record": None,
        "precision": "day",
        "kind": "earliest_known",
        "spotify": "2018-07-27",
        "status": "partial",
        "source": "MusicBrainz, first-release-date of the recording, title and artist match checked",
        "url": "https://musicbrainz.org/search?query=Ah-Mer-Ah-Su%20Heartbreaker&type=recording",
        "checked": "2026-09-04",
        "note": "",
    },
    # Our Lady J — Picture of a Man
    "0rK7QTyYjhPFadLH2YDl84": {
        "first_public": "2013-08-21",
        "first_record": None,
        "precision": "day",
        "kind": "earliest_known",
        "spotify": "2013-08-21",
        "status": "partial",
        "source": "Spotify, track page metadata, read in session",
        "url": "https://open.spotify.com/",
        "checked": "2026-09-04",
        "note": "No entry in MusicBrainz or Discogs. Platform date, not corroborated. Self-titled EP. Replaces a false MusicBrainz match.",
    },
    # Zemmoa, Tessa Ia, Trans-X — Mi Amor Soy Yo
    "4QnHaiWq1oJiTgMnRFE0q8": {
        "first_public": "2021-11-19",
        "first_record": None,
        "precision": "day",
        "kind": "earliest_known",
        "spotify": "2021-11-19",
        "status": "partial",
        "source": "MusicBrainz, first-release-date of the recording, title and artist match checked",
        "url": "https://musicbrainz.org/search?query=Zemmoa%20Mi%20Amor%20Soy%20Yo&type=recording",
        "checked": "2026-09-04",
        "note": "",
    },
    # Aderet — היו לילות
    "0DZapO0gUF8XZpk2bu8AeL": {
        "first_public": "2026-03-05",
        "first_record": None,
        "precision": "day",
        "kind": "earliest_known",
        "spotify": "2026-03-05",
        "status": "partial",
        "source": "Spotify, track page metadata, read in session",
        "url": "https://open.spotify.com/",
        "checked": "2026-09-04",
        "note": "No entry in MusicBrainz or Discogs. Platform date, not corroborated. The song takes up an older Israeli standard; what is dated here is this artist's rendition, not the material.",
    },
    # Shyraa Roy, Kashif Ali — Duniya
    "07m5UbUHOQCofRK16k83Eg": {
        "first_public": "2022-05-02",
        "first_record": None,
        "precision": "day",
        "kind": "earliest_known",
        "spotify": "2022-05-02",
        "status": "partial",
        "source": "Spotify, track page metadata, read in session",
        "url": "https://open.spotify.com/",
        "checked": "2026-09-04",
        "note": "No entry in MusicBrainz or Discogs. Platform date, not corroborated.",
    },
    # Haiifa Magic — To2i W Far2a3i
    "5srzGYocC4qYFvckQm5AfC": {
        "first_public": "2018-07-14",
        "first_record": None,
        "precision": "day",
        "kind": "earliest_known",
        "spotify": "2018-07-14",
        "status": "partial",
        "source": "Spotify, track page metadata, read in session",
        "url": "https://open.spotify.com/",
        "checked": "2026-09-04",
        "note": "No entry in MusicBrainz or Discogs. Platform date, not corroborated.",
    },
    # Harisu — Snow White  [pilote]
    "4X6PkqzKUvWWKoq4YiiM1V": {
        "first_public": "2012-07-09",
        "first_record": None,
        "precision": "day",
        "kind": "first",
        "spotify": "2012-07-09",
        "status": "verified",
        "source": "ManiaDB and Apple Music Korea, entries for The Queen (11th Anniversary), dates and tracklists read",
        "url": "https://www.maniadb.com/album/711327",
        "checked": "2026-09-04",
        "note": "The Korean title is 백설공주 on Bugs and ManiaDB, but Apple Music Korea itself lists “Snow White”: the English title comes from the distributor, Danal Entertainment, not from a platform's translation. Both forms coexist, the Korean one in the music databases, the English one in distribution metadata. ManiaDB gives RELEASE DATE 2012-07-09, ALBUM TYPE digital single, six tracks of which three are instrumentals. Despite the word Anniversary this is not a compilation but a comeback single of new songs, so an early suspicion of reissue was wrong. The song is absent from her five studio albums of 2001 to 2007.",
    },
    # Harisu — 애지몽
    "7l8D5tXUVsdq95VQWn034C": {
        "first_public": "2025-08-24",
        "first_record": None,
        "precision": "day",
        "kind": "first",
        "spotify": "2025-08-24",
        "status": "verified",
        "source": "Bugs, entry for the single 애지몽 (愛知夢), date, tracks and credits read",
        "url": "https://music.bugs.co.kr/album/20749608",
        "checked": "2026-09-04",
        "note": "발매일 2025.08.24, a single with four tracks, two of them instrumentals. The sleeve text states that the song was written and composed for Harisu's voice by 최비룡 and 최고야, with full studio credits. A 2025 creation, not a reissue.",
    },
    # Harisu — 됐거든
    "1EPYnBjYhYHcNthEnVWk18": {
        "first_public": "2025-08-24",
        "first_record": None,
        "precision": "day",
        "kind": "first",
        "spotify": "2025-08-24",
        "status": "verified",
        "source": "Bugs, entry for the single 애지몽 (愛知夢), track 2, date and credits read",
        "url": "https://music.bugs.co.kr/album/20749608",
        "checked": "2026-09-04",
        "note": "The same single of 24 August 2025. The sleeve text describes 됐거든 as Harisu's first dance-trot number, made for her by the same writers. A 2025 creation, not a reissue.",
    },
    # Hương Giang — Anh Ta Bỏ Em Rồi
    "4Ykmj47fulJ1FTeCXctW91": {
        "first_public": "2019-10-31",
        "first_record": None,
        "precision": "day",
        "kind": "earliest_known",
        "spotify": "2019-10-31",
        "status": "partial",
        "source": "Spotify, track page metadata, read in session",
        "url": "https://open.spotify.com/",
        "checked": "2026-09-04",
        "note": "No entry in MusicBrainz or Discogs. Platform date, not corroborated. Self-titled single. Replaces a false MusicBrainz match that gave 1995.",
    },
    # Cindy Thái Tài — Giọt Tình
    "1N1F6UsRGILux57U0YbxJQ": {
        "first_public": 2007,
        "first_record": None,
        "precision": "year",
        "kind": "earliest_known",
        "spotify": "2007-01-01",
        "status": "partial",
        "source": "Spotify, track page metadata, read in session",
        "url": "https://open.spotify.com/",
        "checked": "2026-09-04",
        "note": "Album Bước Chân Hoàn Vũ 2. Spotify's 1 January is filler, hence a date given to the year.",
    },
    # Bell Nuntita — Paradise
    "0NOume8OgBz4FCnP1QVr9A": {
        "first_public": "2012-07-19",
        "first_record": None,
        "precision": "day",
        "kind": "earliest_known",
        "spotify": "2012-07-19",
        "status": "partial",
        "source": "Spotify, track page metadata, read in session",
        "url": "https://open.spotify.com/",
        "checked": "2026-09-04",
        "note": "No entry in MusicBrainz or Discogs. Platform date, not corroborated.",
    },
    # Lucinta Luna, Dede Satria — Mantan Tanpa Status - Lucinta Luna Version
    "46uGvJVhYHOVRRNnRPbkYm": {
        "first_public": "2019-04-29",
        "first_record": None,
        "precision": "day",
        "kind": "earliest_known",
        "spotify": "2019-04-29",
        "status": "partial",
        "source": "Spotify, track page metadata, read in session",
        "url": "https://open.spotify.com/",
        "checked": "2026-09-04",
        "note": "No entry in MusicBrainz or Discogs. Platform date, not corroborated.",
    },
    # Ai Haruna — さそり座の女
    "0GSW6V6GJc4xYi8c5jOu60": {
        "first_public": "2018-03-21",
        "first_record": None,
        "precision": "day",
        "kind": "earliest_known",
        "spotify": "2018-03-21",
        "status": "partial",
        "source": "Spotify metadata read in session; MusicBrainz gave 2020-06-19",
        "url": "https://open.spotify.com/",
        "checked": "2026-09-04",
        "note": "The platform column turned out to be earlier than the MusicBrainz date. The earlier of the two is kept.",
    },
    # Ataru Nakamura — きみがすきだよ
    "6EjxYTyXiBzJz6PeOvPiou": {
        "first_public": "2018-12-05",
        "first_record": None,
        "precision": "day",
        "kind": "earliest_known",
        "spotify": "2018-12-05",
        "status": "partial",
        "source": "Spotify, track page metadata, read in session",
        "url": "https://open.spotify.com/",
        "checked": "2026-09-04",
        "note": "No entry in MusicBrainz or Discogs. Platform date, not corroborated. Album るつぼ. Absent from the Discogs tracklists consulted for her 2006 and 2007 releases.",
    },
    # Lia Larsson, Tone Sekelius, Lisa Ajax — VI ÄR SVERIGE (VM-låt 2023)
    "4yBfzgV6YA9dTKP8KUD35j": {
        "first_public": "2023-06-30",
        "first_record": None,
        "precision": "day",
        "kind": "first",
        "spotify": "2024-02-23",
        "status": "verified",
        "source": "Apple Music, single page",
        "url": "https://music.apple.com/us/album/vi-%C3%A4r-sverige-vm-l%C3%A5t-2023-single/1693428525",
        "checked": "2026-09-04",
        "note": "An earlier date of 2024 came from MusicBrainz and was wrong: this is the official 2023 World Cup song.",
    },
    # Patricia Ribeiro — Conquistador
    "0pe5NUU9uGwFpj637ot84D": {
        "first_public": "2020-05-15",
        "first_record": None,
        "precision": "day",
        "kind": "earliest_known",
        "spotify": "2020-05-15",
        "status": "partial",
        "source": "Spotify, track page metadata, read in session",
        "url": "https://open.spotify.com/",
        "checked": "2026-09-04",
        "note": "No entry in MusicBrainz or Discogs. Platform date, not corroborated. Album Lotaria do Amor.",
    },
    # Urias — Diaba
    "4Zhxtm6x56wEiRtSMAl28n": {
        "first_public": "2019-08-20",
        "first_record": None,
        "precision": "day",
        "kind": "earliest_known",
        "spotify": "2019-08-20",
        "status": "partial",
        "source": "MusicBrainz, first-release-date of the recording, title and artist match checked",
        "url": "https://musicbrainz.org/search?query=Urias%20Diaba&type=recording",
        "checked": "2026-09-04",
        "note": "",
    },
    # Urias — Foi Mal
    "1RmXibCbfLIVrN8ZRdoYbW": {
        "first_public": "2020-05-27",
        "first_record": None,
        "precision": "day",
        "kind": "earliest_known",
        "spotify": "2022-01-14",
        "status": "partial",
        "source": "MusicBrainz, first-release-date of the recording, title and artist match checked",
        "url": "https://musicbrainz.org/search?query=Urias%20Foi%20Mal&type=recording",
        "checked": "2026-09-04",
        "note": "",
    },
    # Liniker — Baby 95
    "4P9LdSPrnQl7KQwml4DUtq": {
        "first_public": "2021-09-09",
        "first_record": None,
        "precision": "day",
        "kind": "earliest_known",
        "spotify": "2021-09-09",
        "status": "partial",
        "source": "MusicBrainz, first-release-date of the recording, title and artist match checked",
        "url": "https://musicbrainz.org/search?query=Liniker%20Baby%2095&type=recording",
        "checked": "2026-09-04",
        "note": "",
    },
    # Linn da Quebrada — Enviadescer
    "1AFPmwB6mGMCcMI2hFh7c8": {
        "first_public": "2016-10-20",
        "first_record": None,
        "precision": "day",
        "kind": "earliest_known",
        "spotify": "2017-10-06",
        "status": "partial",
        "source": "MusicBrainz, first-release-date of the recording, title and artist match checked",
        "url": "https://musicbrainz.org/search?query=Linn%20da%20Quebrada%20Enviadescer&type=recording",
        "checked": "2026-09-04",
        "note": "",
    },
    # Irmãs de Pau, Brunoso — Medley do Submundo
    "6D7zTed8zrkuKBPca2AqSI": {
        "first_public": "2023-02-14",
        "first_record": None,
        "precision": "day",
        "kind": "earliest_known",
        "spotify": "2023-01-14",
        "status": "partial",
        "source": "MusicBrainz, first-release-date of the recording, title and artist match checked",
        "url": "https://musicbrainz.org/search?query=Irm%C3%A3s%20de%20Pau%20Medley%20do%20Submundo&type=recording",
        "checked": "2026-09-04",
        "note": "",
    },
    # PEDRO SAMPAIO, Irmãs de Pau, Mc Gw, Tasha Ka — SEQUÊNCIA CUNT (feat. Clementaum)
    "7bNgXJ9MgGG7xOkyz9SLOY": {
        "first_public": "2025-11-18",
        "first_record": None,
        "precision": "day",
        "kind": "earliest_known",
        "spotify": "2025-11-18",
        "status": "partial",
        "source": "MusicBrainz, first-release-date of the recording, title and artist match checked",
        "url": "https://musicbrainz.org/search?query=PEDRO%20SAMPAIO%20SEQU%C3%8ANCIA%20CUNT%20%28feat.%20Clementaum%29&type=recording",
        "checked": "2026-09-04",
        "note": "",
    },
    # Mulher Pepita, Brabo — Parceira
    "4WhyfhjZaX6AVjAZslQAFs": {
        "first_public": "2018-03-02",
        "first_record": None,
        "precision": "day",
        "kind": "earliest_known",
        "spotify": "2018-03-02",
        "status": "partial",
        "source": "MusicBrainz, first-release-date of the recording, title and artist match checked",
        "url": "https://musicbrainz.org/search?query=Mulher%20Pepita%20Parceira&type=recording",
        "checked": "2026-09-04",
        "note": "",
    },
    # Backxwash — BLACK SAILOR MOON
    "3FysLYckiMCMzjYLIgo45U": {
        "first_public": "2018-12-01",
        "first_record": None,
        "precision": "day",
        "kind": "earliest_known",
        "spotify": "2018-12-01",
        "status": "partial",
        "source": "Spotify, track page metadata, read in session",
        "url": "https://open.spotify.com/",
        "checked": "2026-09-04",
        "note": "No entry in MusicBrainz or Discogs. Platform date, not corroborated. Self-titled album. Replaces a false MusicBrainz match that gave 2019-11-15.",
    },
    # Backxwash, Ada Rook — I LIE HERE BURIED WITH MY RINGS AND MY DRESS
    "37OSQm8Gy5strUT24vn6ef": {
        "first_public": "2021-05-07",
        "first_record": None,
        "precision": "day",
        "kind": "earliest_known",
        "spotify": "2021-06-20",
        "status": "partial",
        "source": "MusicBrainz, first-release-date of the recording, title and artist match checked",
        "url": "https://musicbrainz.org/search?query=Backxwash%20I%20LIE%20HERE%20BURIED%20WITH%20MY%20RINGS%20AND%20MY%20DRESSES&type=recording",
        "checked": "2026-09-04",
        "note": "",
    },
    # Angel Maxine, Wanlov The Kubolor, Sister Deb — Wo Fie
    "3QF7smzmw2WWm7M1jt2Rac": {
        "first_public": "2021-07-26",
        "first_record": None,
        "precision": "day",
        "kind": "earliest_known",
        "spotify": "2021-07-26",
        "status": "partial",
        "source": "MusicBrainz, first-release-date of the recording, title and artist match checked",
        "url": "https://musicbrainz.org/search?query=Angel%20Maxine%20Wo%20Fie&type=recording",
        "checked": "2026-09-04",
        "note": "",
    },
    # Quay Dash — Queen Of This Shit
    "6JrmHzxhaaavRtlXTOhm63": {
        "first_public": "2017-10-26",
        "first_record": None,
        "precision": "day",
        "kind": "earliest_known",
        "spotify": "2017-10-26",
        "status": "partial",
        "source": "MusicBrainz, first-release-date of the recording, title and artist match checked",
        "url": "https://musicbrainz.org/search?query=Quay%20Dash%20Queen%20Of%20This%20Shit&type=recording",
        "checked": "2026-09-04",
        "note": "",
    },
    # Ms. Boogie — Breakdown
    "2iqTYCPRTqojxM7QJvBtk2": {
        "first_public": "2024-01-12",
        "first_record": None,
        "precision": "day",
        "kind": "earliest_known",
        "spotify": "2024-01-12",
        "status": "partial",
        "source": "MusicBrainz, first-release-date of the recording, title and artist match checked",
        "url": "https://musicbrainz.org/search?query=Ms.%20Boogie%20Breakdown&type=recording",
        "checked": "2026-09-04",
        "note": "",
    },
    # Andra Venus — Power
    "3eBY8aZZdWNnNhNbc8B0yp": {
        "first_public": "2024-05-16",
        "first_record": None,
        "precision": "day",
        "kind": "earliest_known",
        "spotify": "2024-05-16",
        "status": "partial",
        "source": "Spotify, track page metadata, read in session",
        "url": "https://open.spotify.com/",
        "checked": "2026-09-04",
        "note": "No entry in MusicBrainz or Discogs. Platform date, not corroborated. EP La Estrella. Replaces a false MusicBrainz match.",
    },
    # Sasha Sathya — AKA LESBIANA SERPIENTA
    "1RkB4Dk0CDzpaSySq91JEA": {
        "first_public": "2021-03-26",
        "first_record": None,
        "precision": "day",
        "kind": "earliest_known",
        "spotify": "2021-03-26",
        "status": "partial",
        "source": "Spotify, track page metadata, read in session",
        "url": "https://open.spotify.com/",
        "checked": "2026-09-04",
        "note": "No entry in MusicBrainz or Discogs. Platform date, not corroborated.",
    },
    # LALLA RAMI — INCHALLAH
    "4UfEEnq70NgLeq7NRfXPiD": {
        "first_public": "2021-12-16",
        "first_record": None,
        "precision": "day",
        "kind": "earliest_known",
        "spotify": "2021-12-16",
        "status": "partial",
        "source": "MusicBrainz, first-release-date of the recording, title and artist match checked",
        "url": "https://musicbrainz.org/search?query=LALLA%20RAMI%20INCHALLAH&type=recording",
        "checked": "2026-09-04",
        "note": "",
    },
    # LALLA RAMI — 9A7BA
    "5nWecUJF2pytSxsSpylzZw": {
        "first_public": "2026-03-27",
        "first_record": None,
        "precision": "day",
        "kind": "earliest_known",
        "spotify": "2026-03-27",
        "status": "partial",
        "source": "Spotify, track page metadata, read in session",
        "url": "https://open.spotify.com/",
        "checked": "2026-09-04",
        "note": "No entry in MusicBrainz or Discogs. Platform date, not corroborated.",
    },
    # Ptite Soeur, neophron — ANFO჻  [pilote]
    "5Gp1fkuPV7CPtzKHfMH0kd": {
        "first_public": "2023-05-29",
        "first_record": None,
        "precision": "day",
        "kind": "first",
        "spotify": "2023-05-30",
        "status": "verified",
        "source": "SoundCloud, display_date field on the track",
        "url": "https://soundcloud.com/ptite-soeur/anfo",
        "checked": "2026-09-04",
        "note": "The file has existed since 14 May 2023 (created_at), but the public date is the 29th.",
    },
    # Ptite Soeur, Gemroz — KAYFABE
    "0A2tFUYLertZLltvvY5uyr": {
        "first_public": "2024-06-30",
        "first_record": None,
        "precision": "day",
        "kind": "earliest_known",
        "spotify": "2024-06-30",
        "status": "partial",
        "source": "MusicBrainz, first-release-date of the recording, title and artist match checked",
        "url": "https://musicbrainz.org/search?query=Ptite%20Soeur%20KAYFABE&type=recording",
        "checked": "2026-09-04",
        "note": "",
    },
    # Romy Haag — Memories Are Made Of This - Radio  [pilote]
    "2lgwylOpGMtkvhwdnUOArt": {
        "first_public": 2002,
        "first_record": None,
        "precision": "year",
        "kind": "earliest_known",
        "spotify": "2008-05-20",
        "status": "partial",
        "source": "Discogs, artist discography 1072839, CD maxi single, Pool label",
        "url": "https://www.discogs.com/artist/1072839",
        "checked": "2026-09-04",
        "note": "The release page itself was not opened. A gap of 6 years against Spotify.",
    },
    # Coccinelle — Chercher la femme  [pilote]
    "4CuivW1JgPauXPA4wYsf5K": {
        "first_public": 1963,
        "first_record": None,
        "precision": "year",
        "kind": "first",
        "spotify": "2004-01-01",
        "status": "verified",
        "source": "Discogs, release 6883852, RCA Victor 86 012 7-inch EP, track A1",
        "url": "https://www.discogs.com/release/6883852",
        "checked": "2026-09-04",
        "note": "Spotify serves the 2004 CD compilation. A gap of 41 years.",
    },
}
